identification= {
    'subj_id':'REC_ID',
    'data_status':"F_STATUS",
    'patient_no': "PATNO",
    'event_name': "EVENT_ID",
    'page_name': "PAG_NAME",
}


demographics = {
    
'Screening___Demographics.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME","SIGNCNST", "CONSNTDT", "APPRDX", "CURRENT_APPRDX", "P3GRP", "BIRTHDT", "GENDER", "HISPLAT", "RAINDALS", "RAASIAN", "RABLACK", "RAHAWOPI", "RAWHITE", "RANOS", "PRJENRDT", "REFERRAL", "DECLINED", "RSNDEC", "EXCLUDED", "RSNEXC", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
    
}

Cognition = { 
    
'Hopkins_Verbal_Learning_Test.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","HVLTRT1", "HVLTRT2", "HVLTRT3", "HVLTRDLY", "HVLTREC", "HVLTFPRL", "HVLTFPUN", "comm", "AGE_ASSESS_HVLT", "DVT_TOTAL_RECALL", "DVT_DELAYED_RECALL", "DVT_RETENTION", "DVT_RECOG_DISC_INDEX", "LAST_UPDATE", "QUERY", "SITE_APRV",),
    
    
'Symbol_Digit_Modalities.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","SDMTOTAL", "SDMTVRSN", "AGE_ASSESS_SDM", "DVSD_SDM", "DVT_SDM", "COMM", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),

    
'Semantic_Fluency.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","VLTANIM", "VLTVEG", "VLTFRIOT", "AGE_ASSESS_SFTANIM", "DVS_SFTANIM", "DVT_SFTANIM", "ORIG_ENTRY", "QUERY", "SITE_APRV",),


'Lexical_Fluency.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT", "LXFLUEF", "LXFLUEA", "LXFLUES", "ORIG_ENTRY", "QUERY", "SITE_APRV",),


'Letter_-_Number_Sequencing__PD_.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","LNS1A", "LNS1B", "LNS1C", "LNS2A", "LNS2B", "LNS2C", "LNS3A", "LNS3B", "LNS3C", "LNS4A", "LNS4B", "LNS4C", "LNS5A", "LNS5B", "LNS5C", "LNS6A", "LNS6B", "LNS6C", "LSN7A", "LNS7B", "LNS7C", "LNS_TOTRA" "AGE_ASSESS_LNS", "DVS_LNS", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),


'Montreal_Cognitive_Assessment__MoCA_.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","MCAALTTM", "MCACUBE", "MCACLCKC", "MCACLCKN", "MCACLCKH", "MCALION", "MCARHINO", "MCACAMEL", "MCAFDS", "MCABDS", "MCAVIGIL", "MCASER7", "MCASNTNC", "MCAVFNUM", "MCAVF", "MCAABSTR", "MCAREC1", "MCAREC2", "MCAREC3", "MCAREC4", "MCAREC5", "MCADATE", "MCAMONTH", "MCAYR", "MCADAY", "MCAPLACE", "MCACITY", "MCATOT", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),


'Benton_Judgment_of_Line_Orientation.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","BJLOT1", "BJLOT2", "BJLOT3", "BJLOT4", "BJLOT5", "BJLOT6", "BJLOT7", "BJLOT8", "BJLOT9", "BJLOT10", "BJLOT11", "BJLOT12", "BJLOT13", "BJLOT14", "BJLOT15", "BJLOT16", "BJLOT17", "BJLOT18", "BJLOT19", "BJLOT20", "BJLOT21", "BJLOT22", "BJLOT23", "BJLOT24", "BJLOT25", "BJLOT26", "BJLOT27", "BJLOT28", "BJLOT29", "BJLOT30", "COMM", "JLO_TOTRAW", "JLO_TOTCALC", "AGE_ASSESS_JLO", "DVS_JLO_MSSA", "DVS_JLO_MSSAE", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),


'Cognition_Function-Short_Form.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","NQCOG22R", "NQCOG24R", "NQCOG25R", "NQCOG40R", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),

'Cognitive_Assessments.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","HVLTRTTM", "HVLTDRTM", "LNORNTTM", "SFTTM", "LNSTM", "SDMTM", "MOCATM", "BSTNTM", "LEXICLTM", "TMTTM", "COMM", "ORIG_ENTRY", "LAST_UPDAT", "QUERY", "SITE_APRV",),


'Cognitive_Categorization.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","PTCGBOTH", "COGDECLN", "FNCDTCOG", "COGSTATE", "COGDXCL", "RVWNPSY", "COGCAT", "COGCAT_TEXT", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
   

'Communication-Short_Form.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","NQCOG01", "NQCOG04", "NQCOG08", "NQCOG10", "NQCOG11", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),


'Trail_Making_A_and_B.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","TMTACMPL", "TMTASEC", "TMTACORR", "TMTBCMPL", "TMTBSEC", "TMTBCORR", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),


'Modified_Boston_Naming_Test.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT", "MBSTNSCR", "MBSTNCRC", "MBSTNCRR", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),

'Benton_Judgment_of_Line_Orientation.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","BJLOT1", "BJLOT2", "BJLOT3", "BJLOT4", "BJLOT5", "BJLOT6", "BJLOT7", "BJLOT8", "BJLOT9", "BJLOT10", "BJLOT11", "BJLOT12", "BJLOT13", "BJLOT14", "BJLOT15", "BJLOT16", "BJLOT17", "BJLOT18", "BJLOT19", "BJLOT20", "BJLOT21", "BJLOT22", "BJLOT23", "BJLOT24", "BJLOT25", "BJLOT26", "BJLOT27", "BJLOT28", "BJLOT29", "BJLOT30", "COMM", "JLO_TOTRAW", "JLO_TOTCALC", "AGE_ASSESS_JLO", "DVS_JLO_MSSA", "DVS_JLO_MSSAE", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
    
}


Npsychiatry = {
   
    'State-Trait_Anxiety_Inventory.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","STAIAD1", "STAIAD2", "STAIAD3", "STAIAD4", "STAIAD5", "STAIAD6", "STAIAD7", "STAIAD8", "STAIAD9", "STAIAD10", "STAIAD11", "STAIAD12", "STAIAD13", "STAIAD14", "STAIAD15", "STAIAD16", "STAIAD17", "STAIAD18", "STAIAD19", "STAIAD20", "STAIAD21", "STAIAD22", "STAIAD23", "STAIAD24", "STAIAD25", "STAIAD26", "STAIAD27", "STAIAD28", "STAIAD29", "STAIAD30", "STAIAD31", "STAIAD31", "STAID32", "STAIAD33", "STAIAD34", "STAID35", "STAID36", "STAIAD37", "STAIAD38", "STAIAD39", "STAID40", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
    
    'QUIP_Current_Short.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","PTINBOTH", "TMGAMBLE", "CNTRLGMB", "TMSEX", "CNTRLSEX", "TMBUY", "CNTRLBUY", "TMEAT", "CNTRLEAT", "TMTORACT", "TMTMTACT", "TMTRWD", "TMDISMED", "CNTRLDSM", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
    
    'Geriatric_Depression_Scale__Short_.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","GDSSATIS", "GDSDROPD", "GDSEMPTY", "GDSBORED", "GDSGSPIR", "GDSAFRAD", "GDSHAPPY", "GDSHLPLS", "GDSHOME", "GDSWRTLS", "GDSENRGY", "GDSHOPLS", "GDSBETER", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
}


Clinical = {
    
'University_of_Pennsylvania_Smell_ID_Test.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","UPSITBK1", "UPSITBK2", "UPSITBK3", "UPSITBK", "NORMATIVE_SCORE", "COMM", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),


'Olfactory_UPSIT.csv': ("SUBJECT_ID", "PROTOCOL_ID", "COMPLT_DATE","SCENT_10_RESPONSE", "SCENT_09_RESPONSE", "SCENT_08_RESPONSE", "SCENT_07_RESPONSE", "SCENT_06_RESPONSE", "SCENT_05_RESPONSE", "SCENT_04_RESPONSE", "SCENT_03_RESPONSE", "SCENT_02_RESPONSE", "SCENT_01_RESPONSE", "SCENT_20_RESPONSE", "SCENT_19_RESPONSE", "SCENT_18_RESPONSE", "SCENT_17_RESPONSE", "SCENT_16_RESPONSE", "SCENT_15_RESPONSE", "SCENT_14_RESPONSE", "SCENT_13_RESPONSE", "SCENT_12_RESPONSE", "SCENT_11_RESPONSE", "SCENT_30_RESPONSE", "SCENT_29_RESPONSE", "SCENT_28_RESPONSE", "SCENT_27_RESPONSE", "SCENT_26_RESPONSE", "SCENT_25_RESPONSE", "SCENT_24_RESPONSE", "SCENT_23_RESPONSE", "SCENT_22_RESPONSE", "SCENT_21_RESPONSE", "SCENT_40_RESPONSE", "SCENT_39_RESPONSE", "SCENT_38_RESPONSE", "SCENT_37_RESPONSE", "SCENT_36_RESPONSE", "SCENT_35_RESPONSE", "SCENT_34_RESPONSE", "SCENT_33_RESPONSE", "SCENT_32_RESPONSE", "SCENT_31_RESPONSE", "SCENT_10_CORRECT", "SCENT_09_ CORRECT", "SCENT_08_ CORRECT", "SCENT_07_ CORRECT", "SCENT_06_ CORRECT", "SCENT_05_ CORRECT", "SCENT_04_ CORRECT", "SCENT_03_ CORRECT", "SCENT_02_ CORRECT", "SCENT_01_ CORRECT", "SCENT_20_ CORRECT", "SCENT_19_ CORRECT", "SCENT_18_ CORRECT", "SCENT_17_ CORRECT", "SCENT_16_ CORRECT", "SCENT_15_ CORRECT", "SCENT_14_ CORRECT", "SCENT_13_ CORRECT", "SCENT_12_ CORRECT", "SCENT_11_ CORRECT", "SCENT_30_ CORRECT", "SCENT_29_ CORRECT", "SCENT_28_ CORRECT", "SCENT_27_ CORRECT", "SCENT_26_ CORRECT", "SCENT_25_ CORRECT", "SCENT_24_ CORRECT", "SCENT_23_ CORRECT", "SCENT_22_ CORRECT", "SCENT_21_ CORRECT", "SCENT_40_ CORRECT", "SCENT_39_ CORRECT", "SCENT_38_ CORRECT", "SCENT_37_ CORRECT", "SCENT_36_ CORRECT", "SCENT_35_ CORRECT", "SCENT_34_ CORRECT", "SCENT_33_ CORRECT", "SCENT_32_ CORRECT", "SCENT_31_ CORRECT", "TOTAL_CORRECT", "UPSIIT_PRCNTGE",),


'REM_Sleep_Disorder_Questionnaire.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","PTCGBOTH", "DRMVIVID", "DRMAGRAC", "DRMNOCTB", "SLPLMBVM", "SLPINJUR", "DRMVERBL", "DRMFIGHT", "DRMUMV", "MVAWAKEN", "DRMREMEM", "SLPDSTRB", "STROKE", "HETRA", "NARCLPSY", "DEPRS", "EPILEPSY", "BRNINFM", "CNSOTH", "CNSOTHCM", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "STE_APRV",),


'Epworth_Sleepiness_Scale.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","PTCGBOTH", "ESS1", "ESS2", "ESS3", "ESS4", "ESS5", "ESS6", "ESS7", "ESS8", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),


'Features_of_REM_Behavior_Disorder.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","REMONSDT", "REMONEST", "RBDDXDT", "RBDDXEST", "ONCLNZP", "ONBENZ", "ONMLATON", "ONSSRI", "ONNORSRI", "ONTRIADP", "ONBTABLK", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
 
'SCOPA-AUT.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","PTCGBOTH", "SCAU1", "SCAU2", "SCAU3", "SCAU4", "SCAU5", "SCAU6","SCAU7", "SCAU8", "SCAU9", "SCAU10", "SCAU11", "SCAU12", "SCAU13", "SCAU14", "SCAU15", "SCAU16", "SCAU17", "SCAU18", "SCAU19", "SCAU20", "SCAU21", "SCAU22", "SCAU23", "SCAU23A", "SCAU23AT", "SCAU24", "SCAU25", "SCAU26A", "SCAU26AT", "SCAU26B", "SCAU26BT", "SCAU26C", "SCAU26CT", "SCAU26D", "SCAU26DT", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),

}


Other = {
    
'Magnetic_Resonance_Imaging.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME","INFODT", "MRICMPLT", "MRIDT", "MRIWDTI", "MRIWRSS", "MRIXFRYN", "MRIRSLT", "PDMEDYN", "ONLDOPA", "ONDOPAG", "ONOTHER", "PDMEDDT", "COMM", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),

    
'MRI_Imaging_Data_Transfer_Information_Source_Document.csv': ("study_subject_id", "11_scan_acquisition_date_mr_E1_C3","12_scan_quality_rating_mr_E1_C3", "13_dti_sequences_E1_C3", "11a_rs_mri_E1_C4", "comment_E1_C7", "other_E1_C7",),


'PPMI_Baseline_Data_02Jul2018.csv': ("SITE", "PATNO","APPRDX", "EVENT_ID", "age", "age_cat", "gen", "EDUCYRS", "educ", "HISPLAT", "race", "fampd_new", "fampd_old", "duration", "ageonset", "agediag", "DOMSIDE", "symptom1", "symptom2", "symptom3", "symptom4", "symptom5", "symptom5_comment", "symptom6", "hy", "NHY", "rigidity", "td_pigd", "td_pigd_old", "tremor", "updrs3_score", "PM_MED_USE", "MSEADLG", "updrs1_score", "NP1COG", "NP1HALL", "NP1DPRS", "NP1ANXS", "NP1APAT", "NP1DDS", "NP1FATG", "updrs2_score", "updrs_totscore", "upsit", "bjlot", "ess", "ess_cat", "gds", "gds_cat", "hvlt_immediaterecall", "HVLTRDLY", "HVLTREC", "HVLTFPRL", "hvlt_discrimination", "hvlt_retention", "Ins", "quip_gamble", "quip_sex", "quip_buy", "quip_eat", "quip_hobby", "quip_pund", "quip_walk", "quip", "quip_any", "rem", "rem_cat", "rem_q6", "scopa_gi", "scopa_ur", "scopa_cv", "scopa_therm", "scopa_pm", "scopa_sex", "scopa", "VLTANIM", "VLTVEG", "VLTFRUIT", "sft", "stai_state", "stai_trait", "stai", "SDMTOTAL", "moca", "CAUDATE_R", "CAUDATE_L", "PUTAMEN_R", "PUTAMEN_L", "r_striatum", "l_striatum", "mean_caudate", "mean_putamen", "mean_striatum", "low_caudate", "hi_caudate", "low_putamen", "hi_putamen", "low_striatum", "hi_striatum", "ai_caudate", "ai_putamen", "ai_striatum", "l_cdr", "r_cdr", "con_striatum", "con_caudate", "con_putamen", "con_cdr", "ips_striatum", "ips_caudate", "ips_putamen", "ips_cdr", "abeta", "asyn", "tau", "ptau", "tau_ab", "ptau_ab", "ptau_tau", "ab_asyn", "tau_sayn", "ptau_asyn", "hemo", "hemo_below", "hemo_above", "hemohi", "urate", "APOE", "SNCA_ rs356181", "SNCA_rs3910105", "APOE_e4", "SNCA_rs356181_cat", "SNCA_rs3910105_cat", "MAPT", "MAPT_cat",), 
    
}

Gender = {

'Screening___Demographics.csv' :("BIRTHDT", "GENDER", "HISPLAT", "RAINDALS", "RAASIAN", "RABLACK", "RAHAWOPI", "RAWHITE", "RANOS",), 
                                     
'Pregnancy_Form.csv':("SPREGPRF", "SPRGRSLT","SPRGCNBF","UPREGPRF", "UPRGRSLT", "UPRGCNBF", "PREG", "PREGDT","'PREGPERF", "'PREGRSLT", 'PREGPRI', 'PREGSPRI', 'CRLACTAT',), 
    
'Current_Medical_Conditions_Log.csv': ("DIAGYR", "DXYREST", "CONDTERM",),
    
'Current_Biospecimen_Analysis_Results.csv' :("DIAGNOSIS",), 
  
'Cognitive_Categorization.csv' :('COGDECLN', 'COGSTATE', 'FNCDTCOG',), 
  
'PASE_-_Household_Activity.csv' :( 'LTHSWRK', 'HVYHSWRK', 'HMREPR', 'LAWNWRK','CAREGVR',), 
    
'Geriatric_Depression_Scale__Short_.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","GDSSATIS", "GDSDROPD", "GDSEMPTY", "GDSBORED", "GDSGSPIR", "GDSAFRAD", "GDSHAPPY", "GDSHLPLS", "GDSHOME", "GDSWRTLS", "GDSENRGY", "GDSHOPLS", "GDSBETER", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),

'Montreal_Cognitive_Assessment__MoCA_.csv': ("REC_ID", "F_STATUS", "PATNO", "EVENT_ID", "PAG_NAME", "INFODT","MCAALTTM", "MCACUBE", "MCACLCKC", "MCACLCKN", "MCACLCKH", "MCALION", "MCARHINO", "MCACAMEL", "MCAFDS", "MCABDS", "MCAVIGIL", "MCASER7", "MCASNTNC", "MCAVFNUM", "MCAVF", "MCAABSTR", "MCAREC1", "MCAREC2", "MCAREC3", "MCAREC4", "MCAREC5", "MCADATE", "MCAMONTH", "MCAYR", "MCADAY", "MCAPLACE", "MCACITY", "MCATOT", "ORIG_ENTRY", "LAST_UPDATE", "QUERY", "SITE_APRV",),
              
}


EXPLANATIONS = {
"nan":"Wearable and Sensor Participation Status",
"REC_ID":"Record ID'",
"F_STATUS":"Data status: Verified, Secured or Locked",
"CNO":"Center Number",
"PATNO":"Patient Number",
"EVENT_ID":"Event Name",
"PAG_NAME":"Page Name",
"INVSTAFF":"Investigator Staff Code",
"AESEQ":"AE#",
"AETERM":"Adverse Event",
"STARTDT":"Start Date",
"STARTEST":"Start Date Estimation",
"STOPDT":"Stop Date",
"STOPEST":"Stop Date Estimation",
"AESEVER":"Severity",
"SAE":"SAE",
"AERELAT":"Relationship to Study",
"RELDSCAN":"Related to DaTSCAN",
"RELLP":"Related to LP",
"RELAV133":"Related to AV-133",
"RELSKBIO":"Related to Skin Biopsy",
"RELFB":"Related to Florbetaben",
"RELPRCDR":"Related to other study procedure",
"PWDTAE":"Premature Withdrawal due to AE",
"AEOUTCOM":"Outcome",
"AEFLUP":"AE Status at final visit",
"VERBATIM":"Verbatim Term",
"LLT_NAME":"Low Level Term",
"PT_CODE":"Preferred Term Code",
"PT_NAME":"Preferred Term Name",
"HLT_NAME":"High Level Term",
"HLGTNAME":"High Level Group Term",
"SOCABBR1":"System Organ Class 1",
"VMEDDRA":"MedDRA Version",
"ORIG_ENTRY":"Date of original data entry",
"LAST_UPDATE":"Date of most recent update to record",
"QUERY":"Any open/pending queries on this record",
"SITE_APRV":"Date site approved the data",
"INFODT":"Event Date",
"SIGNCNST":"Signed Consent",
"AVCNSTDT":"AV-133 Informed consent date",
"INEX1":"Inclusion Exclusion question 1",
"INEX2":"Inclusion Exclusion question 2",
"INEX3":"Inclusion Exclusion question 3",
"INEX4":"Inclusion Exclusion question 4",
"INEX5":"Inclusion Exclusion question 5",
"INEX6":"Inclusion Exclusion question 6",
"INEX7":"Inclusion Exclusion question 7",
"INVEVLBF":"Study physician able to evaluate before",
"VITLTMBF":"Vital Sign Time - before",
"SYSSUPBF":"Supine BP - systolic - before",
"DIASUPBF":"Supine BP - diastolic - before",
"HRSUPBF":"Supine heart rate - before",
"SPREGPRF":"Serum Pregnancy test performed",
"SPRGRSLT":"Serum Pregnancy test result",
"SPRGCNBF":"Serum Preg result confirmed prior to",
"UPREGPRF":"Urine Pregnancy test performed",
"UPRGRSLT":"Urine Pregnancy test result",
"UPRGCNBF":"Urine Preg result confirmed prior to",
"INJECTTM":"Time of Injection",
"VITLTMAF":"Vital Sign Time - after",
"SYSSUPAF":"Supine BP - systolic - after",
"DIASUPAF":"Supine BP - diastolic - after",
"HRSUPAF":"Supine heart rate - after",
"PETCMPLT":"PET scan completed?",
"PETDT":"Date PET scan completed",
"INVEVLAF":"Study physician able to evaluate after",
"XFRYN":"Data transfer",
"VMATRSLT":"VMAT-2 PET Interpretation Report",
"COMM":"Comments",
"BBNKSHR":"Agree to share contact info-brain bank",
"BBNKINDT":"Date brain bank  contact info obtained",
"BBNKXFDT":"Date brain bank contact info transferred",
"GENDER":"Gender",
"DIAGNOSIS":"Appropriate Diagnosis",
"CLINICAL_EVENT":"Event Name",
"TYPE":"Type",
"TESTNAME":"Test Name",
"TESTVALUE":"Test Value",
"UNITS":"Units of Measure",
"RUNDATE":"Run Date",
"PROJECTID":"Project ID for Analysis",
"PI_NAME":"Name of Project PI",
"PI_INSTITUTION":"Name of PI Instituion",
"SPECIMEN_NO":"Specimen Number",
"CUSTODIAL_DOMAIN":"Custodial Domain",
"ALIAS_ID":"Patient Number",
"QUANTITY":"Quantity",
"QUANTITY_UNITS":"Quantity Units",
"NUM_AVAILABLE":"Num Aliquots Available",
"ADDTL_STOCK_AVAIL_ON_REQ":"Addition Stock Available upon Request",
"VENDOR":"Cell Line Creator",
"REPROGRAMMING_METHOD":"Reprogramming Method",
"CELL_TYPE":"Cell Type",
"PARENT_SPECIMEN_ID":"Parent Specimen ID",
"PARENT_CELL_TYPE":"Parent Cell Type",
"CELLS_PER_CONTAINER":"Cells per Container",
"PASSAGE_NUMBER_AT_FREEZE":"Passage Number at Freeze",
"KARYOTYPE":"Karotype Result",
"KARYOTYPE_PROCEDURE":"Karotype Procedure",
"IDENTITY_TEST":"Identity Test Result",
"PLURIPOTENCY":"Pluripotency Result",
"MYCOPLASMA":"Mycoplasma Result",
"STERILITY_TEST":"Sterility Test Result",
"FREEZING_MEDIA":"Freezing Media",
"CHNGAPDX":"New category (change)",
"NEWSOA":"Subject starting with new SOA",
"CHNGFVIS":"First visit conducted in new category",
"RECNSTDT":"Date of re-consent",
"CLCKPII":"Clock Drawing-Time-one hand points to 2",
"CLCK2HND":"Clock Drawing-Time-exactly 2 hands",
"CLCKNMRK":"Clock Drawing-Time-absence of marks",
"CLCKNUIN":"Clock Drawing-Number-Numbers inside",
"CLCKALNU":"Clock Drawing-Number-All 1-12 present",
"CLCKNUSP":"Clock Draw-Spacing-Num eq space from Num",
"CLCKNUED":"Clock Drw-Spacing-Num eq space from edge",
"CLCKTOT":"Clock Drawing-Total Score",
"PSLVL":"Confidence level-motor signs of PS",
"DCNOMTR":"No motor signs consistent with PS",
"DCRTREM":"Present for dx PD-Rest Tremor",
"DCRIGID":"Present for dx PD-Rigidity",
"DCBRADY":"Present for dx PD-Bradykinesia",
"DFPGDIST":"Postural and gait dist are typical of PD",
"DFOTH":"Other signs related to PS",
"DFOTHCM":"Other signs related to PS - comment",
"PRIMDIAG":"Most  likely primary diagnosis",
"OTHNEURO":"Other neurological disorder(s) (specify)",
"CLDXCHNG":"Change in clinical diagnosis",
"DXFDTIMG":"Factors in diagnosis-imaging data",
"DXFCLSGN":"Factors in diagnosis-clinical signs",
"DXFRSPMD":"Factors in diagnosis-response to PD med",
"DXFNATHX":"Factors in diagnosis-natural history",
"DXFOTH":"Factors in diagnosis-other",
"DXFOTHCM":"Factors in diagnosis-other comment",
"MNGCHNG":"Change in clinical management",
"MNGTRTSX":"Current management-treat symptoms of PD",
"MNGTRIAL":"Current management-enrolled in trial",
"MNGTRTOT":"Current management-treat other than PD",
"MNGDXTST":"Current management-diagnostic testing",
"MNGNOTRT":"Current management-no treatment",
"OTNEURVS":"Seen another neurologist",
"NEURWKDX":"Other neurologist working diagnosis",
"BLDLAB":"Blood for safety labs",
"BLDSHPDT":"Date shipped to central lab",
"VIEWNAME":"Data Table",
"ITM_NAME":"Item Name",
"CDL_NAME":"Codelist Name",
"CODE":"Codes",
"DECODE":"Decoded Value",
"PTCGBOTH":"Source of Information",
"COGDECLN":"Experienced cognitive decline",
"FNCDTCOG":"Functional impairment due to cognitive",
"COGSTATE":"Cognitive State",
"COGDXCL":"Level of confidence cognitive diagnosis",
"RVWNPSY":"Review neuropsychological tests",
"COGCAT":"Cognitive T Score",
"COGCAT_TEXT":"Cognitive T Score Description",
"HVLTRTTM":"HVLT-R immediate Recall Time",
"HVLTDRTM":"HVLT-R Delayed Recall/Recog Time",
"LNORNTTM":"Benton Judgement of Line Orient Time",
"SFTTM":"Semantic Fluency Time",
"LNSTM":"Letter Number Sequencing Time",
"SDMTM":"Symbol Digit Modalities Time",
"MOCATM":"MoCA Time",
"TMTTM":"Trail Making Time",
"BSTNTM":"Boston Naming Test Time",
"LEXICLTM":"Lexical Fluency Time",
"COMPLT":"Did the subject complete the study?",
"WDRSN":"Reason for withdrawal",
"WDRSNCM":"Withdrawal comment",
"WDDT":"Withdrawal date",
"CMSEQ":"Row #",
"CMTRT":"Medication",
"CMDOSE":"Dose",
"CMDOSU":"Units",
"CMDOSFRQ":"Frequency",
"ROUTE":"Route",
"ONGOING":"Ongoing",
"CMINDC":"Indication",
"DISMED":"PD Med ?",
"TOTDDOSE":"Total Daily Dose",
"RECNO":"WHO RECNO",
"SEQNO1":"WHO SEQNO1",
"SEQNO2":"WHO SEQNO2",
"WHODRUG":"WHO DRUG NAME",
"EXCLMED":"Exclusionary Med flag",
"LEDD":"LEDD calculation for PD medication",
"PD_MOTOR_MED":"Medication affects PD Motor assessments 0=No; 1=Yes",
"ALLOCATED_DATE":"Allocation Date",
"CONFIRMED_DATE":"Confirmed Date",
"CONTAINER_TYPE":"Container Type",
"DISPOSITION":"Disposition",
"SAMPLEID":"Coriell Sample ID",
"SITE_ID":"Site Name",
"SMS_SUBJECT_ID":"Internal ST Identifier",
"STATUS":"Status",
"STUDYID":"Study Name",
"VOLUME_RECEIVED":"Volume Received",
"VOLUME_RECEIVED_UNITS":"Volume Received Units",
"PARENTID":"Parent Sample ID",
"COLLECTION_DATE":"Sample Collection Date",
"REP_GENDER":"Gender",
"QC":"QC Status",
"QC_DATE":"QC Date",
"MASS_UG":"Mass ug",
"CONCENTRATION":"Concentration",
"RATIO_260_280":"Ratio 260 280",
"RIN":"RIN",
"PARAMETERLIST":"Parameter List",
"PARAMID":"Parameter ID",
"VALUE":"Value",
"TESTINSTANCE":"Test Instance",
"TESTDATE":"Test date and time",
"BIRTHDT":"Date of Birth",
"LACCNO":"Lab Accession Number",
"LCOLLDT":"Collection Date",
"COLLTM":"Collection Time",
"LRECDT":"Date Received",
"RECTM":"Time Received",
"LRPTDT":"Report Date",
"RPTTM":"Report Time",
"LABCODE":"Lab Code",
"LGROUP":"Lab Group",
"LTSTCODE":"Test Code",
"LTSTNAME":"Test Name",
"LVISTYPE":"Visit Type",
"LSIRES":"SI Result",
"LSIUNIT":"SI Unit",
"LSILORNG":"SI Low Range",
"LSIHIRNG":"SI High Range",
"LUSRES":"US Result",
"LUSUNIT":"US Unit",
"LUSLORNG":"US Low Range",
"LUSHIRNG":"US High Range",
"LRESFLG":"Result Flag",
"LTSTCOMM":"Test Specific Comments",
"SEQNO":"Sequence Number",
"CONDCAT":"Current Conditions Category",
"DIAGYR":"Year of Diagnosis",
"DXYREST":"Diagnosis Year Estimated?",
"CONDTERM":"Current Conditions Description",
"RESOLVD":"Resolved",
"RESYR":"Year of Resolution",
"DATSCAN":"DAT imaging and SPECT scan completed",
"DATSCNDT":"SPECT Scan date",
"SCNLOC":"Location scan was completed",
"SCNINJCT":"Scan injection",
"DATXFRYN":"DAT imaging transferred",
"VSINTRPT":"Visual Interpretation Report",
"VSRPTELG":"Visual Interpretation Rpt (eligible/not)",
"RSLTNGAE":"AEs as a result of DAT scan",
"DBSYN":"Does subject have DBS",
"DBSOFFPR":"DBS turned off prior MDS-UPDRS III Off",
"DBSRSNON":"Reason DBS left on",
"DBSOFFTM":"Time DBS turned off prior to OFF Prt III",
"DBSONTM":"Time DBS turned on after the OFF Prt III",
"AERELDEV":"Related to study device",
"AERELDV":"Related to study device-alt version",
"AEACTDEV":"Action taken with study device",
"AEACTNON":"Action/Treatment - None",
"AEACTOTR":"Action - other treatment required",
"AEACTDRT":"Action - device returned",
"AEACTWDS":"Action - perm wearable study discontinue",
"AEOUT8":"AE Primary Outcome   v8",
"CNCLSTAT":"Conclusion - subject status",
"WDRSN5":"Reason for withdrawal (alternate list 5)",
"DGBSST":"Digital biomarker-participation status",
"DGCNSTDT":"Digital Biomarker Informed consent date",
"NOINCNTV":"No incentive to participate",
"NORSLTRT":"Results not returned to participant",
"CNCRNBRD":"Concern about research burden",
"TRVOUTUS":"Resides/Travels outside USA frequently",
"NOCROTPH":"Does not want to carry another phone",
"NOWIFIHM":"No WIFI at home",
"OTHRSN":"Other",
"OTHRSNCM":"Other Reason, specify",
"DEVICESN":"Serial Number of Device",
"WIFIHM":"Does the subject have WIFI at home",
"WRTHNDNR":"Which hand normally write with",
"DISPDT":"Date Dispensed",
"DEVRET":"Was device returned",
"RETDT":"Date Returned",
"DEVDISPB":"Final device status",
"DFSTROKE":"Excessive stroke risk factors",
"DFRSKFCT":"Unusual or atypical risk factors",
"DFPRESNT":"Unusual or atypical presenting features",
"DFRPROG":"Very rapid progression",
"DFSTATIC":"Static or little change",
"DFHEMPRK":"Hemiparkinsonism longer than 6 years",
"DFAGESX":"Onset before age 30",
"DFOTHCRS":"Unusual course - Other, specify",
"DFCRSCM":"Unusual course - comment",
"DFRTREMP":"Resting tremor present",
"DFRTREMA":"Resting tremor absent",
"DFPATREM":"Prominent action tremor",
"DFOTHTRM":"Tremor - Other, specify",
"DFTREMCM":"Tremor - comment",
"DFRIGIDP":"Rigidity is present and typical for PD",
"DFRIGIDA":"Rigidity is absent",
"DFAXRIG":"Axial rigidity excess of distal rigidty",
"DFUNIRIG":"Marked unilateral or asymmetric rigidity",
"DFTONE":"Additional type of increased tone",
"DFOTHRIG":"Rigidity - Other, specify",
"DFRIGCM":"Rigidity - comment",
"DFBRADYP":"Bradykinesia present and typical for PD",
"DFBRADYA":"Bradykinesia is absent",
"DFAKINES":"Pure Akinesia (without rigidity, tremor)",
"DFBRPLUS":"Bradykinesia not account for rapid movem",
"DFOTHABR":"Akinesia/Bradykinesia - Other, specify",
"DFABRCM":"Akinesia/Bradykinesia - comment",
"DFGAIT":"Wide-based gait or ataxia",
"DFFREEZ":"Prominent freezing early in course",
"DFFALLS":"Likely to fall if not extra careful",
"DFOTHPG":"Postural or gait dist - Other, specify",
"DFPGCM":"Postural or gait disturbances - comment",
"DFPSYCH":"Psychiatric",
"DFCOGNIT":"Cognitive",
"DFDYSTON":"Dystonia",
"DFCHOREA":"Chorea",
"DFMYOCLO":"Myoclonus",
"DFOTHHYP":"Hyperkinesias - Other, specify",
"DFHYPCM":"Other hyperkinesias - comment",
"DFHEMTRO":"Presence of body hemiatrophy",
"DFPSHYPO":"Postural hypotension",
"DFSEXDYS":"Sexual dysfunction",
"DFURDYS":"Urinary dysfunction",
"DFBWLDYS":"Bowel dysfunction",
"DFOCULO":"Oculomotor disturbances",
"DFEYELID":"Eyelid disturbances",
"DFNEURAB":"Other neurological abnormalities",
"DFDOPRSP":"Little or no response to levodopa",
"DFRAPSPE":"Presence of very rapid speech",
"DFBULBAR":"Presence of dysphagia/bulbar dysfunction",
"DFCTSCAN":"CTsuggestive of another cause",
"DFMRI":"MRI suggestive of another cause",
"DFATYP":"Anything unusual/atypical about disease",
"STAFFCD":"Examiner",
"PSLVL2":"Confidence level-motor signs of PS",
"SHLDUNSV":"Should  come in for unsched visit",
"WILLUNSV":"Willing to  come in for unsched visit",
"BLDDNA":"DNA Blood Sample",
"BLDDNADT":"DNA Blood Sample Collection Date",
"BLDVOLML":"Volume of blood collected (milliliters)",
"DNASHPDT":"Date DNA sample shipped",
"DONATPLN":"Did subject complete the donation plan",
"IMAGE_ID":"LONI image UID",
"Measure":"DTI Measure",
"Tissue":"Brain tissue being measured",
"ROI1":"Left Rostral",
"ROI2":"Left Middle",
"ROI3":"Left Caudal",
"ROI4":"Right Rostral",
"ROI5":"Right Middle",
"ROI6":"Right Caudal",
"REF1":"Left Reference",
"REF2":"Right Reference",
"FRZGT1W":"Freezing of gait in past week",
"FLNFR1W":"Falls not related to freezing in past wk",
"FRZGT12M":"Freezing of gait in past 12 months",
"FLNFR12M":"Falls not rel to freezing past 12 months",
"INJFRHIP":"Fracture of hip or lower limb",
"INJFRUE":"Fracture of upper extremity",
"INJFRSKL":"Skull fracture",
"INJFROTH":"Other fracture",
"OTHFRCM":"Other fracture, please specify",
"HINJNOLC":"head injury without loss consciousness",
"HINJLOC2":"head injury, lost conscious",
"INJSTCH":"Laceration requiring sutures(stitches)",
"INJOTH":"Other Injury",
"INJOTHCM":"Other injury, please specify",
"FLLDRVIS":"Fall resulted in dr visit",
"FLLERVIS":"Fall resulted in ER visit",
"FLLHOSP":"Fall resulted in hospitalization",
"FLLSURG":"Fall resulted in surgery",
"FLLINST":"Fall resulted in institutionalization",
"DEVTYPA":"Device Name",
"DEVDISP":"Device Disposition",
"RMANUM":"RMA Number",
"RETDTWH":"Date returned  (to final destination)",
"RPTDT":"Date of report",
"DEVDEF":"Device Deficiency",
"AEDTDEF":"Deficiency resulted in AE",
"RTSPONS":"Device returned to sponsor",
"ADDLACT":"Additional action taken",
"WRIST":"Which wrist",
"WRISTCM":"Wrist circumference (cm)",
"WTCHNTCH":"Watch-Notch-end of band toward face",
"XFRDT":"Transfer Date",
"EKGPERF":"EKG performed",
"EKGTM":"Time of ECG",
"HR":"Heart Rate",
"PRINTRVL":"PR Interval",
"QRS":"QRS Duration",
"QTINTRVL":"QT Interval",
"QTC":"QTC",
"QTCF":"QTCF",
"QTCB":"QTCB",
"EKGRSLT":"EKG results interpretation",
"EKGCSCM":"EKG Abnormal, clinically signif comment",
"ESS1":"Sitting and reading",
"ESS2":"Watching TV",
"ESS3":"Sitting, inactive in a public place",
"ESS4":"As a passenger in a car for an hour",
"ESS5":"Lying down to rest in the afternoon",
"ESS6":"Sitting and talking to someone",
"ESS7":"Sitting quietly after lunch",
"ESS8":"In a car, while stopped in traffic",
"BIOMOM":"Biological Mother",
"BIOMOMPD":"Biological Mother with PD",
"BIODAD":"Biological Father",
"BIODADPD":"Biological Father with PD",
"FULSIB":"Full Siblings",
"FULSIBPD":"Full Siblings with PD",
"HAFSIB":"Half Siblings",
"HAFSIBPD":"Half Siblings with PD",
"MAGPAR":"Maternal Grandparents",
"MAGPARPD":"Maternal Grandparents with PD",
"PAGPAR":"Paternal Grandparents",
"PAGPARPD":"Paternal Grandparents with PD",
"MATAU":"Maternal Aunts and Uncles",
"MATAUPD":"Maternal Aunts and Uncles with PD",
"PATAU":"Paternal Aunts and Uncles",
"PATAUPD":"Paternal Aunts and Uncles with PD",
"KIDSNUM":"How many children do you have",
"KIDSPD":"How many children with PD",
"FHXDISTR":"Family History Packet distributed",
"FBCNSTDT":"Florbetaben Informed consent date",
"FBATVS":"Which visit was Florbetaben done at",
"ONOFFBN":"Capture (medication state)",
"NOFNFRSN":"Reason Full Active not done ON and OFF",
"FATFPRF":"Full Active Test OFF performed",
"FATFDT":"Full Active Test OFF date performed",
"FATFDVST":"Full Active Test OFF device set",
"FATNPRF":"Full Active Test ON performed",
"FATNDT":"Full Active Test ON date performed",
"LSTDSMIN":"How long since last dose - minutes",
"FATNDVST":"Full Active Test ON device set",
"FOSTATUS":"FOUND STATUS",
"FOCONSENTDT":"Date signed consent form received",
"FOFOLLOWST":"FOUND follow-up status",
"FOFOLLOWMO":"Number of Months followed in FOUND",
"FNDSHR":"Agree to share contact info for FOUND",
"FNDINFDT":"Date FOUND  contact info obtained",
"FNDXFRDT":"Date FOUND contact info transferred",
"SRDXDATE":"Date self-reported diagnosis reported",
"FOPTRDX":"Subject reported diagnosis",
"FOPTRDXOTHER":"Subject reported diagnosis - other specify",
"COHORT":"Cohort (1-asymptomatic relatives, 2-true controls, 3 PD)",
"SP_U":"Speed base walking (m/sec)",
"RA_AMP_U":"Right arm amplitude base walking (deg)",
"LA_AMP_U":"Left arm amplitude base walking (deg)",
"RA_STD_U":"Right arm variability base walking (%)",
"LA_STD_U":"Right arm variability base walking (%)",
"SYM_U":"Arms symmetry base walking (%)",
"R_JERK_U":"Jerk Right base walking (deg/sec^3)",
"L_JERK_U":"Jerk Left base walking (deg/sec^3)",
"ASA_U":"ASA base walking (%)",
"ASYM _IND_U":"Asymmetry index base walking (%)",
"TRA_U":"Trunk Rotation Asymmetry base walking (%)",
"T_AMP_U":"Average trunk amplitude base walking (deg)",
"CAD_U":"Cadence base walking (step/min)",
"STR_T_U":"Average stride time base walking (sec)",
"STR_CV_U":"Stride CV base walking (%)",
"STEP_REG_U":"Step Regularity base walking (g^2)",
"STEP_SYM_U":"Step Symmetry base walking",
"JERK_T_U":"Jerk base walking (m/sec^3)",
"SP__DT":"Dual task speed walking (m/sec)",
"RA_AMP_DT":"Right arm amplitude dual task walking (deg)",
"LA_AMP_DT":"Left arm amplitude dual task walking (deg)",
"RA_STD_DT":"Right arm variability dual task walking (%)",
"LA_STD_DT":"Right arm variability dual task walking (%)",
"SYM_DT":"Arms symmetry dual task walking (%)",
"R_JERK_DT":"Jerk Right dual task walking (deg/sec^3)",
"L_JERK_DT":"Jerk Left dual task walking (deg/sec^3)",
"ASA_DT":"ASA dual task walking (%)",
"ASYM _IND_DT":"Asymmetry index dual task walking (%)",
"TRA_DT":"Trunk Rotation Asymmetry dual task walking (%)",
"T_AMP_DT":"Average trunk amplitude dual task walking (deg)",
"CAD_DT":"Cadence dual task walking (step/min)",
"STR_T_DT":"Average stride time dual task walking (sec)",
"STR_CV_DT":"Stride CV dual task walking (%)",
"STEP_REG_DT":"Step Regularity dual task walking (g^2)",
"STEP_SYM_DT":"Step Symmetry dual task walking",
"JERK_T_DT":"Jerk dual task walking (m/sec^3)",
"SW_VEL_OP":"Eyes open sway velocity (m/sec)",
"SW_PATH_OP":"Eyes open sway path (m/sec^2)",
"SW_FREQ_OP":"Centroidal frequency eyes open sway (HZ)",
"SW_JERK_OP":"Jerk eyes open sway (m/sec^3)",
"SW_VEL_CL":"Eyes close sway velocity (m/sec)",
"SW_PATH_CL":"Eyes close sway path (m/sec^2)",
"SW_FREQ_CL":"Centroidal frequency eyes close sway (HZ)",
"SW_JERK_CL":"Jerk eyes close sway (m/sec^3)",
"TUG1_DUR":"TUG1 duration (sec)",
"TUG1_STEP_NUM":"TUG1 number of step (#number)",
"TUG1_STRAIGHT_DUR":"TUG1 Average step duration during straight  walking (sec)",
"TUG1_TURNS_DUR":"TUG1 Average step duration during turns (sec)",
"TUG1_STEP_REG":"TUG1 Step regularity (g^2)",
"TUG1_STEP_SYM":"TUG1 step symmetry",
"TUG2_DUR":"TUG2 duration (sec)",
"TUG2_STEP_NUM":"TUG2 number of step (#number)",
"TUG2_STRAIGHT_DUR":"TUG2 Average step duration during straight  walking (sec)",
"TUG2_TURNS_DUR":"TUG2 Average step duration during turns (sec)",
"TUG2_STEP_REG":"TUG2 Step regularity (g^2)",
"TUG2_STEP_SYM":"TUG2 step symmetry",
"GAITCMPT":"Was gait assessent completed",
"GAITVS":"What visit was gait assessment performed",
"HXORTHO":"History of orthopedic injury, surgery",
"RARMLCM":"Right arm length in centimeters",
"LARMLCM":"Left arm length in centimeters",
"RLEGLCM":"Right leg length in centimeters",
"LLEGLCM":"Left leg length in centimeters",
"WALK10TM":"Time to walk 10 meters (seconds)",
"DUAL10TM":"Time to walk 10 meters dual task (sec)",
"DUALSUBN":"Number of subtractions in Dual task",
"DUALMSTK":"Number of mistakes in Dual subtractions",
"GINEX1":"Inclusion Exclusion question 1-substudy",
"GINEX1A":"Inclusion Exclusion question 1-Prodromal",
"GINEX2":"Inclusion Exclusion question 2-substudy",
"GINEX3":"Inclusion Exclusion question 3-substudy",
"GINEX4":"Inclusion Exclusion question 4-substudy",
"GINEX5":"Inclusion Exclusion question 5-substudy",
"GINEXCM":"Comment",
"GDSSATIS":"Basically satisfied with your life?",
"GDSDROPD":"Dropped many activities and interests?",
"GDSEMPTY":"Feel that your life is empty?",
"GDSBORED":"Often get bored?",
"GDSGSPIR":"In good spirits most of the time?",
"GDSAFRAD":"Afraid something bad will happen to you?",
"GDSHAPPY":"Feel happy most of the time",
"GDSHLPLS":"Often feel helpless?",
"GDSHOME":"Prefer to stay at home?",
"GDSMEMRY":"More problems with memory than most?",
"GDSALIVE":"Wonderful to be alive now?",
"GDSWRTLS":"Feel pretty worthless the way you are?",
"GDSENRGY":"Feel full of energy?",
"GDSHOPLS":"Feel that your situation is hopeless?",
"GDSBETER":"Most people are better off than you are?",
"SEQ_NO":"Sequence Number",
"GENCOUNS":"Have genetic counseling",
"GENCNSPP":"Genetic counseling prior or post",
"GENCNSDT":"Date of genetic counseling",
"GENCNSBY":"Counseling provided by",
"PESEQ":"Number",
"PECAT":"Category",
"ABNORM":"Response",
"ABNORMCM":"Comment",
"HVLTRT1":"Immediate Recall Trial 1",
"HVLTRT2":"Immediate Recall Trial 2",
"HVLTRT3":"Immediate Recall Trial 3",
"HVLTRDLY":"Delayed Recall",
"HVLTREC":"Recognition",
"HVLTFPRL":"Recognition - false positives, related",
"HVLTFPUN":"Recognition - false positives, unrelated",
"HVLTVRSN":"HVLT-R Test Booklet Version used",
"AGE_ASSESS_HVLT":"Age at Assessment - HVLT",
"DVT_TOTAL_RECALL":"Derived-Total Recall T-Score",
"DVT_DELAYED_RECALL":"Derived-Delayed Recall T-Score",
"DVT_RETENTION":"Derived-Retention T-Score",
"DVT_RECOG_DISC_INDEX":"Derived-Recog. Discrim. Index T-Score",
"IRBAPPDT":"Date consent approved by IRB",
"ICFAPPDT":"Date consent approved by IRB",
"CONSNTDT":"Informed consent date",
"ICFINIT":"Participant initial ICF",
"ICFPAMND":"Protocol Amendment",
"ICFIAMND":"ICF Amendment",
"ICFPRTCH":"Participant initiated changes",
"ICFPRVIS":"ICF completed per visit",
"ICFEND":"End of Study ICF",
"ICFSXFR":"Reconsented due to site transfer",
"AMENDNOC":"Amendment Number (char)",
"DTASMSHR":"Consent to share data/samples",
"DNASHR":"Consent to share DNA/RNA",
"FUTCNTCT":"Consent for future contact",
"CNTBRTS":"Consent to contact by Brain/Tissue Bank",
"CNTVER":"Consent to contact by Verily Study team",
"IMAGTYPB":"Type of Imaging Performed",
"IMAGDT":"Date Imaging Performed",
"IMAGVIS":"Visit Imaging Performed",
"CALLDT":"Date CTCC Notified",
"CALLERID":"Caller Staff Code",
"CTCCSTAFF":"CTCC Staff Code",
"SAEDT":"Serious Adverse Event Date",
"TERM":"Premature Withdrawal",
"TERMDT":"Date of withdrawal",
"TERMVIS":"Last Visit Prior to Withdrawal",
"INITMD":"Initiation of PD Medication",
"INITMDDT":"Date of PD Med Initiation",
"INITMDVS":"Visit prior to PD Med Initiation",
"DXCHNG":"Change of Diagnosis",
"DXCHNGDT":"Date of Change of Diagnosis",
"INOSTD":"Participation in another study",
"INOSTDDT":"Date of participation in another study",
"INOSTDEN":"End date of participation in other study",
"INOSDTP":"Type of other study participating in",
"PREG":"Is Pregnancy being Reported?",
"PREGDT":"Date of Pregnancy",
"DEATH":"Death",
"DEATHDT":"Date of Death",
"TAPTRM":"TAP Withdrawal",
"TAPTRMDT":"TAP Withdrawal Date",
"TAPTRMVS":"TAP Withdrawal Visit",
"STRPLCVS":"ST Replaces Visit",
"STVIS":"Visit Replaced with ST Event",
"COHRG":"Change from cohort to registry",
"COHRGDT":"Date changed from cohort to registry",
"COHRGVS":"Visit Prior to change cohort to registry",
"RGCOH":"Change from registry to cohort",
"RGCOHDT":"Date changed from registry to cohort",
"RGCOHVS":"Visit Prior to change registry to cohort",
"SWD24":"SWEDD remaining/returning after 24 mo",
"SWD24CDT":"SWEDD remaining/returning reconsent date",
"FRGOLP":"Permission to forego lumbar puncture",
"FRGOLPDT":"Permission to forego LP date",
"PHENOCNV":"Report of Phenoconversion",
"PHNCNVDT":"Date of Phenoconversion",
"PHNCNVVS":"Visit phenoconversion determined",
"TEXT":"Incident Details",
"protocol_id":"Protocol ID",
"site_number":"Site Number",
"scan_date":"Scan Acquisition Date",
"imaging_center_name":"Imaging Site Name",
"site_name":"Clinical Site Name",
"weight":"Weight",
"weight_unit":"Weight Unit",
"ligand":"Radiopharmaceutical",
"batch_number":"Batch Number",
"injection_site":"Site of Injection",
"pass_qc":"Passed QC",
"expiration_date":"Expiration Date",
"expiration_time":"Expiration Time",
"injection_volume":"Volume of Injection",
"injection_volume_unit":"Injection Volume Unit",
"initial_activity_converted":"Initial Activity Converted to MBq",
"initial_activity_time_hh":"Activity in Syringe Measured Time Hour",
"initial_activity_time_mm":"Activity in Syringe Measured Time Minute",
"residual_activity_converted":"Residual Activity Converted to MBq",
"residual_activity_time_hh":"Residual Activity Measured Time Hour",
"residual_activity_time_mm":"Residual Activity Measured Time Minute",
"injection_time_hh":"Injection Time Hour",
"injection_time_mm":"Injection Time Minute",
"total_dose_calc":"Total Dose Calculation in MBq",
"camera":"Camera",
"trans_one_file_name":"50Min. Transmission File Name",
"trans_one_start_time_hh":"90Min. Transmission Start Time Hour",
"trans_one_start_time_mm":"90Min. Transmission Start Time Minute",
"emiss_one_file_name":"50Min. Emission File Name",
"emiss_one_start_time_hh":"90Min. Emission Start Time Hour",
"emiss_one_start_time_mm":"90Min. Emission Start Time Minute",
"trans_two_file_name":"80Min. Transmission File Name",
"trans_two_start_time_hh":"80Min. Transmission Start Time Hour",
"trans_two_start_time_mm":"80Min. Transmission Start Time Minute",
"emiss_two_file_name":"80Min. Emission File Name",
"emiss_two_start_time_hh":"80Min. Emission Start Time Hour",
"emiss_two_start_time_mm":"80Min. Emission Start Time Minute",
"scan_quality_rating_pet":"PET Scan Quality Rating",
"pet_image_acceptable":"Is PET Scan Acceptable for Submission to Image Database?",
"11_scan_acquisition_date_mr":"scan acquisition date",
"11a_rs_mri":"resting state mr",
"12_scan_quality_rating_mr":"scan quality rating",
"13_dti_sequences":"dti sequences",
"comments":"Technical comments",
"SUBJECT_NUMBER":"Subject ID",
"VISIT_NUMBER":"Scan Number",
"TIMEPOINT":"Imaging Time point",
"RCAUD-S":"SBR OccipUnited of the RCAUD-S",
"RPUTANT-S":"SBR OccipUnited of the RPUTANT-S",
"RPUTPOST-S":"SBR OccipUnited of the RPUTPOST-S",
"LCAUD-S":"SBR OccipUnited of the LCAUD-S",
"LPUTANT-S":"SBR OccipUnited of the LPUTANT-S",
"LPUTPOST-S":"SBR OccipUnited of the LPUTPOST-S",
"study_subject_id":"PPMI Subject ID",
"01_site_number_E1_C2":"Clinical site number",
"03_visit_number_E1_C2":"Visit number scan was acquired on.",
"04_scan_acquisition_date_spect_E1_C2":"SPECT scan date",
"05_scan_start_time_E1_C2":"Emission scan start time",
"06_date_injected_E1_C2":"Date the injection took place",
"07_time_injected_E1_C2":"Time the injection was administered",
"08_actual_dose_injected_E1_C2":"Total dose injected",
"08a_actual_dose_unit_E1_C2":"Total dose units",
"09_scan_quality_rating_spect_E1_C2":"IND\'s SPECT overall image quality rating assessment",
"10_spect_image_acceptable_E1_C2":"Is the scan acceptable for submission into the image database",
"comment_E1_C7":"Technical issue identified",
"other_E1_C7":"Other specify for technical issue identified",
"weight_derived":"Weight in kg",
"trans_one_stop_time_hh":"90Min. Transmission Stop Time Hour",
"trans_one_stop_time_mm":"90Min. Transmission Stop Time Minute",
"emiss_one_stop_time_hh":"90Min. Emission Stop Time Hour",
"emiss_one_stop_time_mm":"90Min. Emission Stop Time Minute",
"cerebellar_cortex_r":"Brain region cerebellar_cortex_r",
"cerebellar_cortex_l":"Brain region cerebellar_cortex_l",
"mesial_temporal_cortex_r":"Brain region mesial_temporal_cortex_r",
"mesial_temporal_cortex_l":"Brain region mesial_temporal_cortex_l",
"pons":"Brain region pons",
"subcortical_white_matter":"Brain region subcortical_white_matter",
"cerebellar_white_matter":"Brain region cerebellar_white_matter",
"rectus_r":"Brain region rectus_r",
"rectus_l":"Brain region rectus_l",
"cingulum_ant_r":"Brain region cingulum_ant_r",
"cingulum_ant_l":"Brain region cingulum_ant_l",
"cingulum_post_r":"Brain region cingulum_post_r",
"cingulum_post_l":"Brain region cingulum_post_l",
"caudate_r":"Brain region caudate_r",
"caudate_l":"Brain region caudate_l",
"putamen_r":"Brain region putamen_r",
"putamen_l":"Brain region putamen_l",
"thalamus_r":"Brain region thalamus_r",
"thalamus_l":"Brain region thalamus_l",
"occipital_cortex_r":"Brain region occipital_cortex_r",
"occipital_cortex_l":"Brain region occipital_cortex_l",
"parietal_cortex_r":"Brain region parietal_cortex_r",
"parietal_cortex_l":"Brain region parietal_cortex_l",
"lateral_temporal_cortex_r":"Brain region lateral_temporal_cortex_r",
"lateral_temporal_cortex_l":"Brain region lateral_temporal_cortex_l",
"orbitofrontal_cortex_r":"Brain region orbitofrontal_cortex_r",
"orbitofrontal_cortex_l":"Brain region orbitofrontal_cortex_l",
"frontal_cortex_r":"Brain region frontal_cortex_r",
"frontal_cortex_l":"Brain region frontal_cortex_l",
"temporal_cortex_r":"Brain region temporal_cortex_r",
"temporal_cortex_l":"Brain region temporal_cortex_l",
"composite_summary":"Brain region composite_summary",
"mean_cerebellum_gray":"Brain region mean_cerebellum_gray",
"mean_whole_cerebellum":"Brain region mean_whole_cerebellum",
"MRSCDATE":"scan acquisition date",
"MRSCQUALITY":"scan quality rating",
"DTISEQ":"dti sequences",
"RSMRISEQ":"resting state mr",
"COMMENTS":"Caller Staff Code",
"11_scan_acquisition_date_mr_E1_C3":"MRI scan date",
"12_scan_quality_rating_mr_E1_C3":"IND\'s MRI overall image quality rating assessment",
"13_dti_sequences_E1_C3":"Have DTI sequences been provided",
"11a_rs_mri_E1_C4":"Has resting state been acquired",
"Study Subject ID":"PPMI Subject ID",
"Protocol ID":"Protocol ID",
"protocol_number_E8_C19":"Protocol Number",
"site_number_E8_C19":"Site Number",
"psg_eval_date_E8_C19":"Eligibility report PSG date",
"rbd_eval_date_E8_C19":"Eligibility report PSG read date",
"psg_file_name_E8_C19":"Results related to PSG file name found in email",
"rbd_eligibility_results_E8_C19":"PSG analysis result for the subject reviewed and evaluation for RBD",
"date_eligibility_report_E8_C19":"Eligibility report completion date",
"percent_rem_sleep_E8_C19":"REM sleep percentage",
"rem_sleep_without_atonia_E8_C19":"REM sleep without atonia (RSWA, Montplasisir 2010) results",
"rem_sleep_scored_E8_C19":"REM sleep results",
"percent_withoutAtonia_epochs":"% of EMG activity amplitude twice BL scored in 30s epochs of 14.5%",
"percent_withoutAtonia_miniEpochs":"% of in 30s with >= 3s mini epochs with phasic activity twice BL amplitude 18%",
"psg_eval_activity_E8_C19":"PSG activity results evaluation",
"CAUDATE_R":"Brain region used for ROI sampling for quantitative analysis caudate_r",
"CAUDATE_L":"Brain region used for ROI sampling for quantitative analysis caudate_l",
"PUTAMEN_R":"Brain region used for ROI sampling for quantitative analysis putamen_r",
"PUTAMEN_L":"Brain region used for ROI sampling for quantitative analysis putamen_l",
"overall_vi_score_E2_C9":"Visual interpreation results",
"scan_date_E3_C10":"Scan acquisition date (scan date)",
"SUBJECT_ID":"Subject ID",
"PROTOCOL_ID":"Study Protocol ID",
"PACKET_ID":"Packet ID",
"BIRTHYEAR":"Year of birth",
"BIRTHMONTH":"Month of birth",
"RACE":"Race",
"RACEOTH":"Race, other",
"ETHNICITY":"Ethnicity",
"PD_DX":"PD Diagnosis",
"PD_FMLYMBR":"Family members with PD",
"LAXATIVE_USE":"Are laxatives used",
"BOWEL_MVMT":"Number of bowel movements per day",
"DECR_SMELL":"Reduced ability to smell",
"ACT_DREAMS":"Patient acts out dreams",
"COMPLT_DATE":"Assessment  completion date",
"SCENT_10_RESPONSE":"Scent 10 Response",
"SCENT_09_RESPONSE":"Scent 09  Response",
"SCENT_08_RESPONSE":"Scent 08  Response",
"SCENT_07_RESPONSE":"Scent 07  Response",
"SCENT_06_RESPONSE":"Scent 06  Response",
"SCENT_05_RESPONSE":"Scent 05  Response",
"SCENT_04_RESPONSE":"Scent 04  Response",
"SCENT_03_RESPONSE":"Scent 03  Response",
"SCENT_02_RESPONSE":"Scent 02  Response",
"SCENT_01_RESPONSE":"Scent 01  Response",
"SCENT_20_RESPONSE":"Scent 20  Response",
"SCENT_19_RESPONSE":"Scent 19  Response",
"SCENT_18_RESPONSE":"Scent 18  Response",
"SCENT_17_RESPONSE":"Scent 17  Response",
"SCENT_16_RESPONSE":"Scent 16  Response",
"SCENT_15_RESPONSE":"Scent 15  Response",
"SCENT_14_RESPONSE":"Scent 14  Response",
"SCENT_13_RESPONSE":"Scent 13  Response",
"SCENT_12_RESPONSE":"Scent 12  Response",
"SCENT_11_RESPONSE":"Scent 11  Response",
"SCENT_30_RESPONSE":"Scent 30  Response",
"SCENT_29_RESPONSE":"Scent 29  Response",
"SCENT_28_RESPONSE":"Scent 28  Response",
"SCENT_27_RESPONSE":"Scent 27  Response",
"SCENT_26_RESPONSE":"Scent 26  Response",
"SCENT_25_RESPONSE":"Scent 25  Response",
"SCENT_24_RESPONSE":"Scent 24  Response",
"SCENT_23_RESPONSE":"Scent 23  Response",
"SCENT_22_RESPONSE":"Scent 22  Response",
"SCENT_21_RESPONSE":"Scent 21  Response",
"SCENT_40_RESPONSE":"Scent 40  Response",
"SCENT_39_RESPONSE":"Scent 39  Response",
"SCENT_38_RESPONSE":"Scent 38  Response",
"SCENT_37_RESPONSE":"Scent 37  Response",
"SCENT_36_RESPONSE":"Scent 36  Response",
"SCENT_35_RESPONSE":"Scent 35  Response",
"SCENT_34_RESPONSE":"Scent 34  Response",
"SCENT_33_RESPONSE":"Scent 33  Response",
"SCENT_32_RESPONSE":"Scent 32  Response",
"SCENT_31_RESPONSE":"Scent 31  Response",
"SCENT_10_CORRECT":"Scent 10 identified correctly",
"SCENT_09_CORRECT":"Scent 9  identified correctly",
"SCENT_08_CORRECT":"Scent 8  identified correctly",
"SCENT_07_CORRECT":"Scent 7 identified correctly",
"SCENT_06_CORRECT":"Scent 6 identified correctly",
"SCENT_05_CORRECT":"Scent 5 identified correctly",
"SCENT_04_CORRECT":"Scent 4 identified correctly",
"SCENT_03_CORRECT":"Scent 3 identified correctly",
"SCENT_02_CORRECT":"Scent 2 identified correctly",
"SCENT_01_CORRECT":"Scent 1 identified correctly",
"SCENT_20_CORRECT":"Scent 20 identified correctly",
"SCENT_19_CORRECT":"Scent 19 identified correctly",
"SCENT_18_CORRECT":"Scent 18 identified correctly",
"SCENT_17_CORRECT":"Scent 17 identified correctly",
"SCENT_16_CORRECT":"Scent 16 identified correctly",
"SCENT_15_CORRECT":"Scent 15 identified correctly",
"SCENT_14_CORRECT":"Scent 14 identified correctly",
"SCENT_13_CORRECT":"Scent 13 identified correctly",
"SCENT_12_CORRECT":"Scent 12 identified correctly",
"SCENT_11_CORRECT":"Scent 11 identified correctly",
"SCENT_30_CORRECT":"Scent 30 identified correctly",
"SCENT_29_CORRECT":"Scent 29 identified correctly",
"SCENT_28_CORRECT":"Scent 28 identified correctly",
"SCENT_27_CORRECT":"Scent 27 identified correctly",
"SCENT_26_CORRECT":"Scent 26 identified correctly",
"SCENT_25_CORRECT":"Scent 25 identified correctly",
"SCENT_24_CORRECT":"Scent 24 identified correctly",
"SCENT_23_CORRECT":"Scent 23 identified correctly",
"SCENT_22_CORRECT":"Scent 22 identified correctly",
"SCENT_21_CORRECT":"Scent 21 identified correctly",
"SCENT_40_CORRECT":"Scent 40 identified correctly",
"SCENT_39_CORRECT":"Scent 39 identified correctly",
"SCENT_38_CORRECT":"Scent 38 identified correctly",
"SCENT_37_CORRECT":"Scent 37 identified correctly",
"SCENT_36_CORRECT":"Scent 36 identified correctly",
"SCENT_35_CORRECT":"Scent 35 identified correctly",
"SCENT_34_CORRECT":"Scent 34 identified correctly",
"SCENT_33_CORRECT":"Scent 33 identified correctly",
"SCENT_32_CORRECT":"Scent 32 identified correctly",
"SCENT_31_CORRECT":"Scent 31 identified correctly",
"TOTAL_CORRECT":"Total Correct Items 0 - 40",
"UPSIIT_PRCNTGE":"UPSIT Percentage 0 - 100",
"INEX8":"Inclusion Exclusion question 8",
"INEX9":"Inclusion question 9",
"INEX10":"Inclusion question 10",
"INEX11":"Inclusion question 11",
"INEX12":"Inclusion question 12",
"INEX13":"Inclusion question 13",
"INEX14":"Inclusion question 14",
"INEX15":"Inclusion question 15",
"INEX16":"Inclusion question 16",
"INEX17":"Inclusion question 17",
"INEX21":"Exclusion question 1",
"INEX22":"Exclusion question 2",
"INEX23":"Exclusion question 3",
"INEX24":"Exclusion question 4",
"INEX25":"Exclusion question 5",
"INEX26":"Exclusion question 6",
"INEX27":"Exclusion question 7",
"INEX28":"Exclusion question 8",
"INEX29":"Exclusion question 9",
"INEX30":"Exclusion question 10",
"INEX31":"Exclusion question 11",
"INEX32":"Exclusion question 12",
"INEX33":"Exclusion question 13",
"INEX34":"Exclusion question 14",
"INEX35":"Exclusion question 15",
"INEX36":"Exclusion question 16",
"INEX37":"Exclusion question 17",
"INEX38":"Exclusion question 18",
"INEX39":"Exclusion question 19",
"INEX40":"Exclusion question 20",
"ELIGIBIL":"Is the Subject eligible for enrollment",
"WAIVERCD":"Protocol Deviation Code",
"IPCNSTDT":"iPSC Informed consent date",
"BLDDRAW":"Blood drawn",
"PDMEDYN":"Is subject on meds for PD",
"PDMEDDT":"Date of most recent dose",
"PDMEDTM":"Time of dose prior to UPDRS",
"WARFBEF":"Subject take warfarin prior to draw",
"HEPBEF":"Subject take heparin prior to draw",
"HXLIVER":"History of liver disease",
"HXMMYLMA":"History of multiple myeloma",
"BLDLTH":"Blood for Lithium Heparin",
"LTHTM":"Time of Lithium Heparin collection",
"LTHINVN":"Number of Lithium Heparin Inversions",
"BLDSST":"Blood for Serum Separator Tube",
"SSTTM":"Time of SST collection",
"SSTSPNTM":"Time SST spin started",
"SSTSPNRT":"SST rate of spin",
"SSTSPNDR":"Duration of SST spin",
"SSTRMTMP":"SST spun at room temperature",
"BLDCPT":"Blood for CPT",
"CPTN":"Total number of CPT tubes",
"CPTTM":"Time of CPT collection",
"CPTSPNTM":"Time CPT spin started",
"CPTSPNRT":"CPT rate of spin",
"CPTSPNDR":"Duration of CPT spin",
"CPTRMTMP":"CPT spun at room temperature",
"SHPCGLPK":"Cold gel packs used for shipping",
"CDIID":"CDI ID",
"TAPDAY":"Days since Baseline TAP assessment",
"REVISION":"Test revision",
"QMAT_OMS":"QMAT OMS",
"QMAT_KEYDOWN":"QMAT keyboard downstroke velocity, combo",
"QMAT_KEYDOWN_RIGHT":"QMAT keyboard downstroke velocity, right hand",
"QMAT_KEYDOWN_LEFT":"QMAT keyboard downstroke velocity, left hand",
"QMAT_PEGCYCLE":"QMAT pegboard cycle duration, combo",
"QMAT_PEGCYCLE_RIGHT":"QMAT pegboard cycle duration, right hand",
"QMAT_PEGCYCLE_LEFT":"QMAT pegboard cycle duration, left hand",
"QMAT_KEYTRAN":"QMAT keyboard transition velocity, combo",
"QMAT_KEYTRAN_RIGHT":"QMAT keyboard transition velocity, right hand",
"QMAT_KEYTRAN_LEFT":"QMAT keyboard transition velocity, left hand",
"DOM_SIDE":"Dominant Side",
"AFF_SIDE":"Most Affected Side",
"SEX":"Sex",
"CONTROL":"Control",
"NOTES":"Notes",
"LMDT":"Date of last meal",
"LMTM":"Time of last meal",
"FASTSTAT":"Fasting Status",
"UASPEC":"Urine Specimen",
"UASPECDT":"Urine Specimen Collection Date",
"UT1TM":"Time of urine tube 1 collection",
"UT1SPNTM":"Time of urine centrifugation",
"UT1SPNRT":"Rate of urine centrifugation",
"UT1SPNDR":"Duration of urine centrifugation",
"UT1CFRG":"Temperature of urine centrifugation",
"UT1FTM":"Time urine tube 1 placed in freezer",
"BLDDRDT":"Date of blood draw",
"BLDRNA":"Blood for PAXgene",
"BLDRNATM":"Time of PAXgene collection",
"RNAFDT":"Date PAXgene sample placed in freezer",
"RNAFTM":"Time PAXgene sample placed in freezer",
"RNASTTMP":"RNA Storage Temperature",
"BLDPLAS":"Blood for plasma level",
"PLASTM":"Time of plasma collection",
"PLASPNTM":"Time of plasma centrifugation",
"PLASPNRT":"Rate of plasma centrifugation",
"PLASPNDR":"Duration of plasma centrifugation",
"PLASCFRG":"Temperature of plasma centrifugation",
"PLASVAFT":"Plasma volume aliquotted after spinning",
"PLAALQN":"Number of aliquot tubes for plasma",
"PLASFTM":"Time plasma samples placed in freezer",
"PLASTTMP":"Plasma storage temperature",
"PLASBFCT":"Plasma - Buffy Coat",
"BLDSER":"Blood for serum",
"BLDSERTM":"Time of serum collection",
"BSSPNTM":"Time of serum centrifugation",
"BSSPNRT":"Rate of serum centrifugation",
"BSSPNDR":"Duration of serum centrifugation",
"BSCFRG":"Temperature of serum centrifugation",
"BSVAFT":"Serum volume aliquotted after spinning",
"BSALQN":"Number of aliquot tubes for serum",
"BSFTM":"Time serum samples placed in freezer",
"BSSTTMP":"Serum storage temperature",
"DurUT1TM":"Duration from time of last intake of food to urine sampling",
"DurUT1SPNTM":"Duration from time of urine collection to start of centrifugation",
"DurUT1FFTM":"Duration from time of urine collection to freezing",
"DurPLASTM":"Duration from time of last intake of food to time of plasma sampling",
"DurPLASSPNTM":"Duration from plasma collection to start of centrifugation",
"DurPLASFFTM":"Duration from plasma collection to freezing",
"DurBLDSERTM":"Duration from time of last intake of food to serum sampling",
"DurSERSPNTM":"Duration from time of serum collection to start of centrifugation",
"DurSERFFTM":"Duration from time of serum collection to freezing",
"LXFLUEF":"Lexical Fluency - letter F",
"LXFLUEA":"Lexical Fluency - letter A",
"LXFLUES":"Lexical Fluency - letter S",
"BJLOT1":"Benton Test Item 1",
"BJLOT2":"Benton Test Item 2",
"BJLOT3":"Benton Test Item 3",
"BJLOT4":"Benton Test Item 4",
"BJLOT5":"Benton Test Item 5",
"BJLOT6":"Benton Test Item 6",
"BJLOT7":"Benton Test Item 7",
"BJLOT8":"Benton Test Item 8",
"BJLOT9":"Benton Test Item 9",
"BJLOT10":"Benton Test Item 10",
"BJLOT11":"Benton Test Item 11",
"BJLOT12":"Benton Test Item 12",
"BJLOT13":"Benton Test Item 13",
"BJLOT14":"Benton Test Item 14",
"BJLOT15":"Benton Test Item 15",
"BJLOT16":"Benton Test Item 16",
"BJLOT17":"Benton Test Item 17",
"BJLOT18":"Benton Test Item 18",
"BJLOT19":"Benton Test Item 19",
"BJLOT20":"Benton Test Item 20",
"BJLOT21":"Benton Test Item 21",
"BJLOT22":"Benton Test Item 22",
"BJLOT23":"Benton Test Item 23",
"BJLOT24":"Benton Test Item 24",
"BJLOT25":"Benton Test Item 25",
"BJLOT26":"Benton Test Item 26",
"BJLOT27":"Benton Test Item 27",
"BJLOT28":"Benton Test Item 28",
"BJLOT29":"Benton Test Item 29",
"BJLOT30":"Benton Test Item 30",
"JLO_TOTRAW":"Line Orientation-Sum 15 item",
"JLO_TOTCALC":"Line Orientation-Sum 15 item X2",
"AGE_ASSESS_JLO":"Age at Assessment - Line Orientation",
"DVS_JLO_MSSA":"Derived-MOANS (Age)",
"DVS_JLO_MSSAE":"Derived-MOANS (Age and Education)",
"LNS1A":"Trial 1a",
"LNS1B":"Trial 1b",
"LNS1C":"Trial 1c",
"LNS2A":"Trial 2a",
"LNS2B":"Trial 2b",
"LNS2C":"Trial 2c",
"LNS3A":"Trial 3a",
"LNS3B":"Trial 3b",
"LNS3C":"Trial 3c",
"LNS4A":"Trial 4a",
"LNS4B":"Trial 4b",
"LNS4C":"Trial 4c",
"LNS5A":"Trial 5a",
"LNS5B":"Trial 5b",
"LNS5C":"Trial 5c",
"LNS6A":"Trial 6a",
"LNS6B":"Trial 6b",
"LNS6C":"Trial 6c",
"LNS7A":"Trial 7a",
"LNS7B":"Trial 7b",
"LNS7C":"Trial 7c",
"LNS_TOTRAW":"LNS-Sum questions 1-7",
"AGE_ASSESS_LNS":"Age at Assessment - LNS",
"DVS_LNS":"Derived-LNS Scaled Score",
"CSFCOLL":"Lumbar puncture for CSF",
"LPNDRSN":"Lumbar puncture not done reason",
"CSFDT":"Date CSF collected",
"CSFNEEDL":"Needle used for CSF",
"CSFMETHD":"Method used for CSF",
"LPSITE":"Lumbar puncture site",
"LPPOSITN":"Lumbar puncture position",
"CSFTM":"Time CSF collected",
"CSFVPRI":"Volume of CSF collected",
"CSFSPNTM":"Time CSF centrifuge",
"CSFSPNRT":"CSF spin rate",
"CSFSPNDR":"Duration of CSF centrifugation",
"CSFCFRG":"CSF spin temperature",
"CSFALQTM":"Time CSF aliquotted",
"CSFVAFT":"Volume of CSF aliquotted",
"CSFALQN":"Number of aliquot tubes",
"SMPDSCRD":"Bloody tap",
"CSFFFTM":"CSF placed in freezer",
"CSFSTTMP":"CSF freezer temp",
"SMPLOCAL":"Sample sent to local lab",
"WBCRSLT":"White blood cell count",
"WBCUNITB":"Wht blood cell count units-mm3 mcL L oth",
"WBCOTHCM":"WBC Units - other",
"RBCRSLT":"Red blood cell count",
"RBCUNITB":"Red blood cell count units-mm3 mcL L oth",
"RBCOTHCM":"RBC Units - other",
"TOPRRSLT":"Total protein",
"TOPRUNIT":"Total protein units",
"TGLCRSLT":"Total glucose",
"TGLCUNIT":"Total glucose units",
"FLUORO":"Was fluoroscopy performed",
"FLUORODT":"Date of fluoroscopy",
"SPFI":"Was lumbar spine film performed",
"SPFIDT":"Date of spine film",
"MHCAT":"Medical History Category",
"MHROW":"Category Seq. Num.",
"MHHX":"Category History",
"MHTERM":"MH Description",
"MHACTRES":"Status of symptom",
"MHDIAGYR":"Year of Diagnosis",
"MCAALTTM":"Alternating Trail Making",
"MCACUBE":"Visuoconstructional Skills (Cube)",
"MCACLCKC":"Visuoconstructional Skills (Clock Cont)",
"MCACLCKN":"Visuoconstructional Skills (Clock Num)",
"MCACLCKH":"Visuoconstructional Skills (Clock Hands)",
"MCALION":"Naming - Lion",
"MCARHINO":"Naming - Rhino",
"MCACAMEL":"Naming - Camel",
"MCAFDS":"Attention - Forward Digit Span",
"MCABDS":"Attention - Backward Digit Span",
"MCAVIGIL":"Attention - Vigilance",
"MCASER7":"Attention - Serial 7s",
"MCASNTNC":"Sentence Repetition",
"MCAVFNUM":"Verbal Fluency - Number of words",
"MCAVF":"Verbal Fluency",
"MCAABSTR":"Abstraction",
"MCAREC1":"Delayed Recall - Face",
"MCAREC2":"Delayed Recall - Velvet",
"MCAREC3":"Delayed Recall - Church",
"MCAREC4":"Delayed Recall - Daisy",
"MCAREC5":"Delayed Recall - Red",
"MCADATE":"Orientation - Date",
"MCAMONTH":"Orientation - Month",
"MCAYR":"Orientation - Year",
"MCADAY":"Orientation - Day",
"MCAPLACE":"Orientation - Place",
"MCACITY":"Orientation - City",
"MCATOT":"MoCA Total Score",
"MBSTNSCR":"Mod Boston Naming Test - spont correct",
"MBSTNCRC":"Mod Boston Naming Test - stimuli correct",
"MBSTNCRR":"Modified Boston Naming Test - correct",
"MBSTNVRS":"Modified Boston Naming Test Version used",
"MSEADLG":"Modified Schwab and England - Overall",
"MRICMPLT":"Brain MRI was completed",
"MRIDT":"Date Brain MRI performed",
"MRIWDTI":"DTI MRI Scan",
"MRIWRSS":"MRI with resting state sequences",
"MRIRSSDF":"MRI resting state seq-diff day PDmed use",
"ONLDOPA":"Is subject taking Levodopa",
"ONDOPAG":"Is subject taking a Dopamine Agonist",
"ONOTHER":"Is subject taking some other medication",
"MRIXFRYN":"MRI data transfer",
"MRIRSLT":"MRI results",
"ASGNCAT":"Assigned Category",
"GENECAT":"Gene Category",
"LRRKCD":"LRRK2 Mutation Code",
"SNCACD":"SNCA Mutation Code",
"MUTRSLT":"Mutation Result",
"ALLELST":"Allele Status",
"UPSRQ":"UP-SRQ Score",
"SBJIDSTE":"Was subject identified by the site",
"SBJIDLST":"How was subject identified",
"SBJIDWRI":"Was subject identified through WRI",
"SBJPRTST":"What is subjects participation status",
"GMUSNCNS":"Signed Consent for Genetic Test Review",
"GMUCNSDT":"Informed consent date for gen test rev",
"PDUNAFF":"PD Status",
"PDDURYRS":"Duration of PD (years)",
"KNOWRSLT":"Know or want to know results",
"RL1DLRRK":"Has 1st degree rel with  LRRK2 mutation",
"RL1DGBA":"Has 1st degree rel with  GBA mutation",
"RL1DSNCA":"Has 1st degree rel with SNCA mutation",
"REL1DPRT":"First degree relative participating",
"PRVGNTST":"Previous genetic testing with results",
"TSTSITEA":"Testing Site results received from",
"TSITACM":"Other Test SIte received from",
"RSLTXFR":"Results transferred",
"RSLTXFDT":"Date results transferred",
"SMPLCOLL":"Was sample collected",
"SMPLTYPE":"Type of sample collected",
"SMPLCLDT":"Date of sample collection",
"SMPLVOL":"Volume of sample collected",
"TSTSITEB":"Testing Site sample shipped to",
"TSITBCM":"Other Test SIte shipped to",
"EVENTDT":"Date of Event",
"NOTIFCRF":"Page",
"NOTIFEVT":"Event",
"NOTIFPRI":"Notification Code - Primary",
"NOTIFSEC":"Notification Code - Secondary",
"NQCOG22R":"NQOL reading and following complex instr",
"NQCOG24R":"NQOL planning/keeping appts not routine",
"NQCOG25R":"NQOL managing time to do most activities",
"NQCOG40R":"NQOL learning new tasks and instructions",
"NQCOG01":"NQOL writing notes to yourself",
"NQCOG04":"NQOL understanding family/friends- phone",
"NQCOG08":"NQOL conversation with small group",
"NQCOG10":"NQOL organizing what you want to say",
"NQCOG11":"NQOL speaking clearly to use the phone",
"NQMOB37":"NQOL able to get on and off toilet",
"NQMOB30":"NQOL able to step up and down curbs",
"NQMOB26":"NQOL able to get in and out of car",
"NQMOB32":"NQOL able to get out of bed into chair",
"NQMOB25":"NQOL able to push open a heavy door",
"NQMOB33":"NQOL able to run errands and shop",
"NQMOB31":"NQOL able to get off floor without help",
"NQMOB28":"NQOL able to go for walk at least 15 min",
"NQUEX29":"NQOL able to turn key in lock",
"NQUEX20":"NQOL able to brush your teeth",
"NQUEX44":"NQOL make call using touch tone key pad",
"NQUEX36":"NQOL able to pick up coins from table",
"NQUEX30":"NQOL able to write with pen or pencil",
"NQUEX28":"NQOL able to open and close a zipper",
"NQUEX33":"NQOL able to wash and dry your body",
"NQUEX37":"NQOL able to shampoo your hair",
"NUPSOURC":"Primary Source of Information",
"NP1COG":"COGNITIVE IMPAIRMENT",
"NP1HALL":"HALLUCINATIONS AND PSYCHOSIS",
"NP1DPRS":"DEPRESSED MOODS",
"NP1ANXS":"ANXIOUS MOOD",
"NP1APAT":"APATHY",
"NP1DDS":"FEATURES-DOPAMINE DYSREGULATION SYNDROME",
"NP1SLPN":"SLEEP PROBLEMS (NIGHT)",
"NP1SLPD":"DAYTIME SLEEPINESS",
"NP1PAIN":"PAIN AND OTHER SENSATIONS",
"NP1URIN":"URINARY PROBLEMS",
"NP1CNST":"CONSTIPATION PROBLEMS",
"NP1LTHD":"LIGHTHEADEDNESS ON STANDING",
"NP1FATG":"FATIGUE",
"NP2SPCH":"SPEECH",
"NP2SALV":"SALIVA + DROOLING",
"NP2SWAL":"CHEWING AND SWALLOWING",
"NP2EAT":"EATING TASKS",
"NP2DRES":"DRESSING",
"NP2HYGN":"HYGIENE",
"NP2HWRT":"HANDWRITING",
"NP2HOBB":"DOING HOBBIES AND OTHER ACTIVITIES",
"NP2TURN":"TURNING IN BED",
"NP2TRMR":"TREMOR",
"NP2RISE":"GETTING OUT OF BED, CAR, OR DEEP CHAIR",
"NP2WALK":"WALKING AND BALANCE",
"NP2FREZ":"FREEZING",
"EXAMTM":"Time Part III was administered",
"PDSTATE":"Subjecté\'s PD state during examination",
"NP3SPCH":"3.1 Speech",
"NP3FACXP":"3.2 Facial expression",
"NP3RIGN":"3.3a Rigidity - Neck",
"NP3RIGRU":"3.3b Rigidity - RUE",
"NP3RIGLU":"3.3c Rigidity - LUE",
"PN3RIGRL":"3.3d Rigidity - RLE",
"NP3RIGLL":"3.3e Rigidity - LLE",
"NP3FTAPR":"3.4a Finger Tapping Right Hand",
"NP3FTAPL":"3.4b Finger Tapping Left Hand",
"NP3HMOVR":"3.5a Hand movements - Right Hand",
"NP3HMOVL":"3.5b Hand movements - Left Hand",
"NP3PRSPR":"3.6a Pronation-Supination - Right Hand",
"NP3PRSPL":"3.6b Pronation-Supination - Left Hand",
"NP3TTAPR":"3.7a Toe tapping - Right foot",
"NP3TTAPL":"3.7b Toe tapping - Left foot",
"NP3LGAGR":"3.8a Leg agility - Right leg",
"NP3LGAGL":"3.8b Leg agility - Left leg",
"NP3RISNG":"3.9 Arising from chair",
"NP3GAIT":"3.10 Gait",
"NP3FRZGT":"3.11 Freezing of gait",
"NP3PSTBL":"3.12 Postural stability",
"NP3POSTR":"3.13 Posture",
"NP3BRADY":"3.14 Global spontaneity of movement",
"NP3PTRMR":"3.15a Postural tremor - Right Hand",
"NP3PTRML":"3.15b Postural tremor - Left hand",
"NP3KTRMR":"3.16a Kinetic tremor - Right hand",
"NP3KTRML":"3.16b Kinetic tremor - Left hand",
"NP3RTARU":"3.17a Rest tremor amplitude - RUE",
"NP3RTALU":"3.17b Rest tremor amplitude - LUE",
"NP3RTARL":"3.17c Rest tremor amplitude - RLE",
"NP3RTALL":"3.17d Rest tremor amplitude - LLE",
"NP3RTALJ":"3.17e Rest tremor amplitude - Lip/jaw",
"NP3RTCON":"3.18 Constancy of rest",
"DYSKPRES":"3.19 Were dyskinesias present",
"DYSKIRAT":"3.20 Did movements interfere with rating",
"NHY":"3.21 Hoehn and Yahr Stage",
"ANNUAL_TIME_BTW_DOSE_NUP":"Hours between dose and NUPDRS (max 99)",
"ON_OFF_DOSE":"PD Med None= ,>=6 hr or PDSTATE OFF and >=3 hr=1,<6 hr=2",
"PD_MED_USE":"0=No,1=Lv,2=Ag,3=Oth,4=1+3,5=1+2,6=2+3,7=1+2+3",
"DBS_STATUS":"0 = OFF, 1 = ON",
"NP4WDYSK":"4.1 Time spent with dyskinesias",
"NP4DYSKI":"4.2 Functional impact of dyskinesias",
"NP4OFF":"4.3 Time spent in the OFF state",
"NP4FLCTI":"4.4 Functional impact of fluctuations",
"NP4FLCTX":"4.5 Complexity of motor fluctuations",
"NP4DYSTN":"4.6 Painful OFF-state dystonia",
"ONPDMED":"did not withhold PD meds",
"FMTRXTAG":"Off Med motor exam tagged as expected",
"FMTRXRPT":"Off Med motor exam repeated as expected",
"NMTRXTAG":"On Med motor exam tagged as expected",
"NMTRXRPT":"On Med motor exam repeated as expected",
"FUTRCNT":"Consent for future research contact",
"FUTRCNDT":"Date Consent for future research contact",
"OTHSTDY":"Name of Study (full title)",
"INTVTYP":"Interventional - specify type",
"STTYPCM":"Other type of study - specify",
"STDYTYP":"Type of study",
"STDYPHSB":"Drug Study Phase",
"SPNPHRM":"Sponsor - Industry/Pharmaceutical",
"SPNFNDTN":"Sponsor - Foundation",
"SPNNIHGV":"Sponsor - NIH/Government",
"SPNLOCAL":"Sponsor - Local",
"SPNOTH":"Sponsor - Other",
"SPNOTHCM":"Other type of sponsor - specify",
"ENROTHDT":"Enrollment Date -other trial",
"ENRDEST":"Enrollment Date - Estimated",
"ENDOTHDT":"End Date -other trial",
"ENDDTEST":"End Date - Estimated",
"STDYIND":"Study Indication",
"STDYINDC":"Study indication- other, specify",
"STDYTRT":"Treatment assignment-placebo/intervent",
"CTRLGOVN":"Clinicaltrials.gov number",
"CTRLGVNA":"Clinicaltrials.gov - Not Applicable",
"DSCR":"Description of page",
"LTHSWRK":"Light housework",
"HVYHSWRK":"Heavy housework",
"HMREPR":"Home repairs",
"LAWNWRK":"Lawn work",
"OUTGARDN":"Outdoor gardening",
"CAREGVR":"Caring for other person(child/dep adult)",
"WRKVL":"Work or volunteer",
"WRKVLHR":"Hours worked or as a volunteer",
"WRKVLACT":"Type phys activity work/volunteer",
"QUESTNO":"Question Number",
"ACTVOFT":"How often participate in activities",
"ACTVSPEC":"Specify activities",
"HRDAYFRQ":"How many hours per day",
"RECRUITMENT_CAT":"Recruitment Category",
"IMAGING_CAT":"Imaging Category",
"ENROLL_DATE":"Enrollment Date",
"ENROLL_CAT":"Enrollment Category",
"ENROLL_STATUS":"Enrollment Status",
"DESCRP_CAT":"Description of Gene Category",
"STATUS_DATE":"Date Enrollment Status Occurred",
"BLDPBMCA":"Blood for PBMC",
"BLPBMCDT":"Date of blood draw for PBMC",
"BLPBMCTM":"Time of blood draw for PBMC",
"SXMO":"Date of Symptom (Month)",
"SXYEAR":"Date of Symptom (Year)",
"PDDXDT":"Date of Parkinson\'s disease diagnosis",
"PDDXEST":"Is the PD diagnosis date estimated?",
"DXTREMOR":"Resting Tremor present at diagnosis?",
"DXRIGID":"Rigidity present at diagnosis?",
"DXBRADY":"Bradykinesia present at diagnosis?",
"DXPOSINS":"Postural instability present at dx?",
"DXOTHSX":"Other symptom present at diagnosis?",
"DXOTHCM":"Other symptoms comment",
"DOMSIDE":"Side predominantly affected at onset",
"NUPDWPRF":"Which MDS-UPDRS exam performed",
"NOUNFRSN":"Reason UPDRS not done in ON and OFF",
"NUPOSMAS":"MDS-UPDRS I,II,IV same time as",
"FULNUPDR":"Was the full UPDRS assessed",
"NUPDRTM":"Time the UPDRS was administered",
"CN1RSP":"CN I",
"CN1CM":"CN I comment",
"CN2RSP":"CN II",
"CN2CM":"CN II comment",
"CN346RSP":"CN III,IV,VI",
"CN346CM":"CN III,IV,VI comment",
"CN5RSP":"CN V",
"CN5CM":"CN V comment",
"CN7RSP":"CN VII",
"CN7CM":"CN VII comment",
"CN8RSP":"CN VIII",
"CN8CM":"CN VIII comment",
"CN910RSP":"CN IX, X",
"CN910CM":"CN IX, X comment",
"CN11RSP":"CN XI",
"CN11CM":"CN XI comment",
"CN12RSP":"CN XII",
"CN12CM":"CN XII comment",
"MSRARSP":"Muscle Strength - right arm",
"MSRACM":"Muscle Strength - right arm comment",
"MSLARSP":"Muscle Strength - left arm",
"MSLACM":"Muscle Strength - left arm comment",
"MSRLRSP":"Muscle Strength - right leg",
"MSRLCM":"Muscle Strength - right leg comment",
"MSLLRSP":"Muscle Strength - left leg",
"MSLLCM":"Muscle Strength - left leg comment",
"COFNRRSP":"Coordination - right finger-to-nose",
"COFNRCM":"Coordination -rt. finger-to-nose comment",
"COFNLRSP":"Coordination - left finger-to-nose",
"COFNLCM":"Coordination -left finger-nose comment",
"COHSRRSP":"Coordination - right heel-to-shin",
"COHSRCM":"Coordination -right heel-to-shin comment",
"COHSLRSP":"Coordination - left heel-to-shin",
"COHSLCM":"Coordination - left heel-to-shin comment",
"SENRARSP":"Sensory - right arm",
"SENRACM":"Sensory - right arm comment",
"SENLARSP":"Sensory - left arm",
"SENLACM":"Sensory - left arm comment",
"SENRLRSP":"Sensory - right leg",
"SENRLCM":"Sensory - right leg comment",
"SENLLRSP":"Sensory - left leg",
"SENLLCM":"Sensory - left leg comment",
"RFLRARSP":"Reflex - right arm",
"RFLRACM":"Reflex - right arm comment",
"RFLLARSP":"Reflex - left arm",
"RFLLACM":"Reflex - left arm comment",
"RFLRLRSP":"Reflex - right leg",
"RFLRLCM":"Reflex - right leg comment",
"RFLLLRSP":"Reflex - left leg",
"RFLLLCM":"Reflex - left leg comment",
"PLRRRSP":"Plantar - right",
"PLRRCM":"Plantar - right comment",
"PLRLRSP":"Plantar - left",
"PLRLCM":"Plantar - left comment",
"CMPLBY2":"Completed by - 2",
"TRBUPCHR":"trouble rising from a chair",
"WRTSMLR":"Handwriting smaller than it once was",
"VOICSFTR":"Voice softer than it once was",
"POORBAL":"Is your balance poor",
"FTSTUCK":"Feet ever seem to get stuck to the floor",
"LSSXPRSS":"Face seems less expressive",
"ARMLGSHK":"Do your arms or legs shake",
"TRBBUTTN":"Do you have trouble buttoning buttons",
"SHUFFLE":"Do you shuffle your feet/take tiny steps",
"MVSLOW":"Move more slowly than others your age",
"TOLDPD":"Been told you have Parkinson\'s disease'",
"PREGPERF":"Pregnancy test",
"PREGRSLT":"Pregnancy test result",
"PREGPRI":"Pregnancy test result before dose",
"PREGSPRI":"Serum Pregnancy test result before dose",
"CRLACTAT":"Currently lactating",
"PTINBOTH":"Source of Information",
"TMGAMBLE":"Gambling-1",
"CNTRLGMB":"Gambling 2",
"TMSEX":"Sex 1",
"CNTRLSEX":"Sex 2",
"TMBUY":"Buying 1",
"CNTRLBUY":"Buying 2",
"TMEAT":"Eating 1",
"CNTRLEAT":"Eating 2",
"TMTORACT":"Other 1",
"TMTMTACT":"Other 2",
"TMTRWD":"Other 3",
"TMDISMED":"Medication 1",
"CNTRLDSM":"Medication 2",
"RADSTAT":"Status of Research Advance Directive",
"RADSTADT":"Date of Research Advance Dir Status",
"ENRSTAFF":"Person performing enrollment",
"ENROLLDT":"Enrollment Date",
"SUBJINIT":"Subject Initials",
"INEXOK":"All incl/excl criteria",
"ENROLLID":"Enrollment ID",
"REMONSDT":"Date of REM symptom onset",
"REMONEST":"REM Symptom Onset Date Estimated?",
"RBDDXDT":"Date of RBD Diagnosis",
"RBDDXEST":"RBD Diagnosis Date Estimated?",
"ONCLNZP":"On Clonazepam",
"ONBENZ":"On other benzodiazepines",
"ONMLATON":"On Melatonin",
"ONSSRI":"On SSRI",
"ONNORSRI":"On Norepinephrine/SRI",
"ONTRIADP":"On Tricyclic anti-depressant",
"ONBTABLK":"On Beta-blocker",
"DRMVIVID":"Vivid Dreams",
"DRMAGRAC":"Aggressive or Action-packed dreams",
"DRMNOCTB":"nocturnal behaviour",
"SLPLMBMV":"move arms/legs during sleep",
"SLPINJUR":"hurt bed partner",
"DRMVERBL":"speaking in sleep",
"DRMFIGHT":"sudden limb movements",
"DRMUMV":"complex movements",
"DRMOBJFL":"things fell down",
"MVAWAKEN":"my movements awake me",
"DRMREMEM":"remember dreams",
"SLPDSTRB":"sleep is disturbed",
"STROKE":"stroke",
"HETRA":"head trauma",
"PARKISM":"parkinsonism",
"RLS":"RLS",
"NARCLPSY":"narcolepsy",
"DEPRS":"depression",
"EPILEPSY":"epilepsy",
"BRNINFM":"inflammatory disease of the brain",
"CNSOTH":"other",
"CNSOTHCM":"specify",
"AGRCNT":"Did subject agree to continue beyond vis",
"CONTFVIS":"First visit after agreeing to continue",
"SCAU1":"SCOPA Item 1",
"SCAU2":"SCOPA Item 2",
"SCAU3":"SCOPA Item 3",
"SCAU4":"SCOPA Item 4",
"SCAU5":"SCOPA Item 5",
"SCAU6":"SCOPA Item 6",
"SCAU7":"SCOPA Item 7",
"SCAU8":"SCOPA Item 8",
"SCAU9":"SCOPA Item 9",
"SCAU10":"SCOPA Item 10",
"SCAU11":"SCOPA Item 11",
"SCAU12":"SCOPA Item 12",
"SCAU13":"SCOPA Item 13",
"SCAU14":"SCOPA Item 14",
"SCAU15":"SCOPA Item 15",
"SCAU16":"SCOPA Item 16",
"SCAU17":"SCOPA Item 17",
"SCAU18":"SCOPA Item 18",
"SCAU19":"SCOPA Item 19",
"SCAU20":"SCOPA Item 20",
"SCAU21":"SCOPA Item 21",
"SCAU22":"SCOPA Item 22",
"SCAU23":"SCOPA Item 23",
"SCAU23A":"SCOPA Item 23a",
"SCAU23AT":"SCOPA Item 23a ED Med",
"SCAU24":"SCOPA Item 24",
"SCAU25":"SCOPA Item 25",
"SCAU26A":"SCOPA Item 26a",
"SCAU26AT":"SCOPA Item 26a med",
"SCAU26B":"SCOPA Item 26b",
"SCAU26BT":"SCOPA Item 26b med",
"SCAU26C":"SCOPA Item 26c",
"SCAU26CT":"SCOPA Item 26c med",
"SCAU26D":"SCOPA Item 26d",
"SCAU26DT":"SCOPA Item 26d med",
"APPRDX":"Appropriate Diagnosis",
"P3GRP":"Prodromal group type",
"HISPLAT":"Ethnicity: Is subject Hispanic/Latino",
"RAINDALS":"Identify self as Am Indian/Alaska Native",
"RAASIAN":"Identify self as Asian",
"RABLACK":"Identify self as Black/African American",
"RAHAWOPI":"Identify self as Hawaiian/Other Pacif Is",
"RAWHITE":"Identify self as White",
"RANOS":"Race not specified",
"RANOSCM":"Race not specified comments",
"PRJENRDT":"Projected Enrollment Date",
"REFERRAL":"Referral source",
"REFERNAM":"Medical Professional referral",
"DECLINED":"Declined",
"RSNDEC":"Reason for Declining",
"EXCLUDED":"Excluded",
"RSNEXC":"Reason for Exclusion",
"CURRENT_APPRDX":"Current Appropriate Diagnosis",
"SDMTOTAL":"Symbol Digit Modalities Total Correct",
"SDMTVRSN":"SDMT Form Version used",
"AGE_ASSESS_SDM":"Age at Assessment - Symbol Digit",
"DVSD_SDM":"Derived-Symbol Digit SD",
"DVT_SDM":"Derived-Symbol Digit T-Score",
"VLTANIM":"Total Number of animals",
"VLTVEG":"Total Number of vegetable",
"VLTFRUIT":"Total Number of fruits",
"AGE_ASSESS_SFTANIM":"Age at Assessment - Sem. Fluency",
"DVS_SFTANIM":"Derived-Sem. Fluency-Animal Scaled Score",
"DVT_SFTANIM":"Derived-Sem. Fluency-Animal T-Score",
"VISSTAT":"Visit completion status",
"VISSTCM":"Visit completion status comment",
"VISMSRSN":"Visit Missed Reason",
"VISMSCM":"Visit Missed Reason Comment",
"ASSESCMP":"Were all assessments for visit completed",
"LGCMED2":"Reviewed ConMed -2",
"LGAE2":"Reviewed AE -2",
"LGCONDTN":"Reviewed Med Conditions",
"COSTAFF":"Coordinator Staff Code",
"TRANSCNO":"Transferring site number",
"SITE_NAME":"Center Name",
"SKBIOCMP":"Was biopsy completed",
"ANSTHADM":"Was anesthesia administered",
"SKBIOLOC":"Location of skin biopsy",
"SBIOLCCM":"Location of biopsy - other, specify",
"SKBIOSID":"Which side of body was biopsy performed",
"BIOCMPLC":"Complications during the biopsy",
"WOUNDCLS":"Type of wound closure",
"WNDCLSCM":"Other wound closure, specify",
"BIOCOLTM":"Time biopsy collected",
"BIOFRGTM":"Time biopsy specimen was refrigerated",
"SHIPDT":"Date shipped",
"SKBICNDT":"Skin biopsy Informed consent date",
"SLFREFDT":"Self Referral Date",
"EDUCYRS":"Number of years of education",
"HANDED":"Handedness",
"STAIAD1":"STAI Question 1",
"STAIAD2":"STAI Question 2",
"STAIAD3":"STAI Question 3",
"STAIAD4":"STAI Question 4",
"STAIAD5":"STAI Question 5",
"STAIAD6":"STAI Question 6",
"STAIAD7":"STAI Question 7",
"STAIAD8":"STAI Question 8",
"STAIAD9":"STAI Question 9",
"STAIAD10":"STAI Question 10",
"STAIAD11":"STAI Question 11",
"STAIAD12":"STAI Question 12",
"STAIAD13":"STAI Question 13",
"STAIAD14":"STAI Question 14",
"STAIAD15":"STAI Question 15",
"STAIAD16":"STAI Question 16",
"STAIAD17":"STAI Question 17",
"STAIAD18":"STAI Question 18",
"STAIAD19":"STAI Question 19",
"STAIAD20":"STAI Question 20",
"STAIAD21":"STAI Question 21",
"STAIAD22":"STAI Question 22",
"STAIAD23":"STAI Question 23",
"STAIAD24":"STAI Question 24",
"STAIAD25":"STAI Question 25",
"STAIAD26":"STAI Question 26",
"STAIAD27":"STAI Question 27",
"STAIAD28":"STAI Question 28",
"STAIAD29":"STAI Question 29",
"STAIAD30":"STAI Question 30",
"STAIAD31":"STAI Question 31",
"STAIAD32":"STAI Question 32",
"STAIAD33":"STAI Question 33",
"STAIAD34":"STAI Question 34",
"STAIAD35":"STAI Question 35",
"STAIAD36":"STAI Question 36",
"STAIAD37":"STAI Question 37",
"STAIAD38":"STAI Question 38",
"STAIAD39":"STAI Question 39",
"STAIAD40":"STAI Question 40",
"PDSURG":"Had surgery for Parkinson disease",
"PDSURGDT":"Date of surgery for Parkinson disease",
"PDSRGEST":"Estimation of surgery date",
"PDSURGTP":"Type of surgery for Parkinson disease",
"PDSRGTPC":"Type of surgery for PD - other, specify",
"PDSURGSD":"Side of surgery for Parkinson disease",
"PDSLGPI":"PD Surgery location - GPi",
"PDSLSTN":"PD Surgery location - STN",
"PDSLOTH":"PD Surgery location - Other",
"PDSLOTCM":"Location of surgery for PD-other,specify",
"PDSLNA":"PD Surgery location - Not Applicable",
"PDSLUNK":"PD Surgery location - Unknown",
"TAPCNSDT":"TAP Informed consent date",
"TAPENRDT":"TAP Enrollment Date",
"OPDMCMPL":"Was OPDM assessment completed",
"OPDMTM":"Time OPDM assessment administered",
"DIGITOGR":"Digitography (keyboard test)",
"PACKEYBD":"Paced Keyboard Test",
"PEGBRD":"Pegboard",
"UNDRSDIR":"How hard to understand directions",
"CONFCORR":"How confident doing task correctly",
"FITSCHED":"How did this fit into your reg schedule",
"NDREMIND":"Did you need to be reminded",
"AFFPPMI":"Affect how felt about main PPMI study",
"CNTACTYN":"Was contact made",
"CNTRSN":"Reason for no contact",
"CNTRSNCM":"Reason for no contact",
"ALIVE":"Is subject still alive",
"DEATHEST":"Death Date Estimated?",
"NCNTCTYN":"new contact information",
"LVCLINDX":"Clinical Diagnosis since last visit",
"TMTACMPL":"Trail Making Part A complete in max time",
"TMTASEC":"Trail Making - Part A (sec)",
"TMTACORR":"Trail Making - Part A  Number correct",
"TMTBCMPL":"Trail Making Part B complete in max time",
"TMTBSEC":"Trail Making - Part B (sec)",
"TMTBCORR":"Trail Making - Part B  Number correct",
"UPSITBK1":"Score from Booklet #1",
"UPSITBK2":"Score from Booklet #2",
"UPSITBK3":"Score from Booklet #3",
"UPSITBK4":"Score from Booklet #4",
"NORMATIVE_SCORE":"Score: x<=18: Anosmia; 18<x<=34/35: Hyposmia; x>34/35: Normosmia; 1+Books missing: Unscored",
"VISCMPLT":"Visit Completed",
"ASSESTYP":"Assessments performed 1=in per, 2=phone",
"CGINPUT":"Caregiver input obtained",
"CGASTYP":"Caregiver input 1=in person, 2=phone",
"VSBYINV":"Visit conducted by investigator",
"VSBYSUBI":"Visit conducted by sub-investigator",
"VSBYCOOR":"Visit conducted by coordinator",
"VSBYCOCO":"Visit conducted by co-coordinator",
"EXCMEDYN":"Advised excl meds is a withdrawal",
"LGFAMHX":"Reviewed Family History",
"WGTKG":"Weight (in Kilograms)",
"HTCM":"Height (in Centimeters)",
"TEMPC":"Temperature (in Celsius)",
"BPARM":"Arm used for blood pressure",
"SYSSUP":"Supine BP - systolic",
"DIASUP":"Supine BP - diastolic",
"HRSUP":"Supine heart rate",
"SYSSTND":"Standing BP - systolic",
"DIASTND":"Standing BP - diastolic",
"HRSTND":"Standing heart rate",
"BLDCOLL":"Blood sample collected",
"BLDCLLDT":"Date of blood collection",
"UADE":"Unexpected Adverse Device Effect",
"WRCNSTDT":"Wearable/Sensor Informed consent date",
"WRSNSSST":"Wearable study-participation status",
"WROTWT":"Wears another type of watch",
"NOWRWT":"Does not wear watch normally",
"NOLKWT":"Does not like style of watch",
"WTCHLL":"Wearing watch can be challenging",
"RELGRSN":"Religious reasons",
"WTCHTYP":"Watch type",
}


